### PR TITLE
Use Alby as extension icon

### PR DESCRIPTION
**Pull request by bumi**
Adding the Alby logo as Extension icon. 

Looks great! much love goes to @GBKS @johnsBeharry

### CODE REVIEW

**Comment by bumi** [comment]
what's the decision here?

**Comment by bumi** [comment]
@MoritzKa I've updated the code to use the sleeping+yellow icon. @MoritzKa can you check it - feel free to approve and merge it when you are happy with it.

**Comment by MoritzKa** [comment]
image
image
image
image

**Comment by bumi** [comment]
@MoritzKa if you like it feel free to approve this PR. 
or does anybody has objections to this?

**Review by MoritzKa — COMMENTED** [review]
ok

**Pull request merged**
