### PR TITLE
Fixed typos fixed at multiple places.

### PR DESCRIPTION
**Pull request by legendarykamal**
### Describe the changes you have made in this PR

Fixed typos fixed at multiple places in the app.

For eg see below it should be `Entertainment` and not `Entertaiment`.

image

### Link this PR to an issue [optional]

Fixes _#ISSUE-NUMBER_

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)
- `feat`: New feature (non-breaking change which adds functionality)
- `feat!`: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- `docs`: Documentation update

### Screenshots of the changes [optional]

_Add screenshots to make your changes easier to understand. You can also add a video here._

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by reneaaron — APPROVED** [review]
Thanks for your PR! 🧡 

tACK

**Review by reneaaron — CHANGES_REQUESTED** [review]
There are still 3 files that still have the translation key with the typo. Please replace it in all of the translation files.

**Comment by legendarykamal** [comment]
Thank you @reneaaron have fixed all the files.

**Review by reneaaron — APPROVED** [review]
Thanks very much for the update! 🙌

**Pull request merged**
