### PR TITLE
feat: add start9 connector

### LINKED ISSUE #677: Add Start9 (EmbassyOS) connector
They have both a LND and c-lightning option.

### PR DESCRIPTION
**Pull request by secondl1ght**
#### Link this PR to an issue
Fixes #677 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

#### Describe the changes you have made in this PR -
I added the Start9 (Embassy) connector, Start9 has a LND and c-lightning option. For now to get this added sooner I thought we could just add the LND option and add in c-lightning at a later date. Start9 services are only available over Tor so I also made note for the user to install the companion app.

#### Screenshots of the changes (If any) -
image

image

#### How Has This Been Tested?
I haven't been able to get the Alby companion app working on linux yet - if someone could test this with the companion app and a lndconnect that would be great!

#### Checklist:

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I have made corresponding changes to the documentation (If Any)

### CODE REVIEW

**Comment by bumi** [comment]
Looks good. can you rebase master?

**Comment by secondl1ght** [comment]
> Looks good. can you rebase master?

Ok I did it - just double check this is what you wanted, it was my first time rebaseing.

**Comment by bumi** [comment]
the diff still looks strange.

**Comment by secondl1ght** [comment]
Ok I reverted the changes - I think you can rebase during merge?

**Pull request merged**
