### PR TITLE
Allow selecting a camera when scanning QR Code

### PR DESCRIPTION
**Pull request by dylancom**
https://github.com/bumi/lightning-browser-extension/issues/195
Can now also be tested from Storybook.

### CODE REVIEW

**Comment by bumi** [comment]
@johnsBeharry do you have a chance to test this?

**Comment by johnsBeharry** [comment]
tried on a few occasions to test this in storybook but I never got it working. should I be testing there or building the extension for this branch?

**Comment by bumi** [comment]
this is a FF build of the branch: https://wormhole.app/nb0KD#iNMrM9ZY4UDT_RRWQ5to1w

**Comment by dylancom** [comment]
@johnsBeharry is correct. I see that the storybook build on netlify is missing the html5-qrcode.min.js asset.

**Pull request merged**
