### PR TITLE
style: change sats icon to alby logo on onboard success screen

### PR DESCRIPTION
**Pull request by secondl1ght**
### Describe the changes you have made in this PR

Updated the sats icon to the Alby logo on the onboard success screen.

### Link this PR to an issue

https://github.com/getAlby/lightning-browser-extension/pull/1153#issuecomment-1186837656

### Type of change (Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes (If any)

image

### How has this been tested?

Tested locally on light and dark modes.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]

**Comment by MoritzKa** [comment]
ok for me based on the screenshot. 

Here we still have the sats logo right?
image

**Comment by escapedcat** [comment]
Good point! @secondl1ght you wanna have a look where else we might need to switch this from "sats" to "bee"?

**Comment by secondl1ght** [comment]
I noticed that but wasn't sure if we wanted to keep the sats symbol in some places? If not then I can update here as well.

**Comment by escapedcat** [comment]
@MoritzKa do we need to keep it somewhere? For all other connectors we show specific connector images, right? We only use this for the Alby account.

**Comment by secondl1ght** [comment]
> @MoritzKa do we need to keep it somewhere? For all other connectors we show specific connector images, right? We only use this for the Alby account.

Some other connectors also show the sats symbol, maybe we want to update all of them to use the connector specific icon?

**Comment by MoritzKa** [comment]
In my opinion, showing the sats symbol in other connectors is okay for now until we´ll have a bigger redesign.

**Comment by bumi** [comment]
+1 at some point these screens will be redesigned anyway. So I would not spend too much time (unless you think changing the image is such a big improvement)

(I cared a bit about the first page, because that's the fist thing the users sees after installing)

**Pull request merged**
