### PR TITLE
style: changed logo on welcome screen

### PR DESCRIPTION
**Pull request by ux3257**
#### Type of change (Remove other not matching type)

- New feature (non-breaking change which adds functionality)

#### Describe the changes you have made in this PR -
Use alby-logo on intro for recognition

#### Screenshots of the changes (If any) -
Bildschirmfoto 2022-04-25 um 20 23 22

#### Checklist:

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by escapedcat** [comment]
I guess I'm missing the background to this. Is there a related issue or was this discussed i.e. on telegram?

**Comment by bumi** [comment]
The topic here was that right now people do not recognize Alby the onboarding screens after installing Alby. 
The screen automatically opens but it is not clear that this is Alby. 

The sats symbol was used before we haf a logo or a name.

**Comment by secondl1ght** [comment]
Looks pretty good, might be a little big though.. can we make Alby smaller?

**Comment by GBKS** [comment]
I like Alby big. Is it possible to use a different visual for dark mode, so the outlines are more visible? Similar issue to the one about the browser icons.

**Comment by escapedcat** [comment]
@MoritzKa @bumi what do you think?

**Comment by bumi** [comment]
+1 for this change. currently there is no element the same as from the install pages and it looks like it is something different. 

maybe @secondl1ght (who has most dark/light mode experience) can check to use different images based on the theme (dark/light mode)?

**Comment by secondl1ght** [comment]
> +1 for this change. currently there is no element the same as from the install pages and it looks like it is something different.
> 
> maybe @secondl1ght (who has most dark/light mode experience) can check to use different images based on the theme (dark/light mode)?

Yes this should be possible, @GBKS do you have a new asset for the Alby dark mode?

**Comment by GBKS** [comment]
Here's an option with a slight color variation of Alby for dark backgrounds ([Figma](https://www.figma.com/file/YVMGfhSHNkK7IWWkCeGUvp/%E2%9A%AB%EF%B8%8FAlby?node-id=46%3A329)).

image

Should be fairly easy to use a different image for dark mode, [here's some info](https://dev.to/dailydevtips1/light-and-dark-mode-image-in-html-lji).

**Comment by secondl1ght** [comment]
> Hmm, I think I'd prefer a white outline.

Yes this one does look a lot different than the original, almost like a different bee.

**Comment by secondl1ght** [comment]
> Should be fairly easy to use a different image for dark mode, [here's some info](https://dev.to/dailydevtips1/light-and-dark-mode-image-in-html-lji).

Users can override the system settings for theme in Alby now so I will have to use a different method to detect the theme, but we already have this implemented so it shouldn't be hard to use for this as well.

**Comment by escapedcat** [comment]
What's blocking this? 😬

**Comment by GBKS** [comment]
You'd have two options for white outlines (if you don't want to change the yellow). You can make the existing outlines white (looks goofy), or add another set of outlines (looks OK, just lots of lines now). Considering that we are using the darker yellow outlines also in the [updated extension icons](https://github.com/getAlby/lightning-browser-extension/pull/1086), that seems like it should be the way to go.

image

**Comment by MoritzKa** [comment]
I like the right version with another set of outlines.

**Comment by escapedcat** [comment]
Decision is: 

> add another set of outlines

**Comment by secondl1ght** [comment]
@ux3257 can you see the latest comments and make the changes or would you like me to take over this PR?

**Comment by secondl1ght** [comment]
Hey @GBKS can you link me to the asset for this? I will finish off this PR and merge it. Thanks!

**Comment by secondl1ght** [comment]
I put in a new PR to finish this off: https://github.com/getAlby/lightning-browser-extension/pull/1153

Thanks @ux3257 for getting this started!

**Pull request closed without merging**
