### PR TITLE
feat: add account menu avatars - avvvatars lib

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

As described in the issue the changes add an Identicon avatar icon to the accounts menu. See screenshots for more infos.

This is the same change as https://github.com/getAlby/lightning-browser-extension/pull/1990 but with the https://avvvatars.com/ lib. https://github.com/nusu/avvvatars 
This lib has types, but the styles are also different. Two styles are available: character and shapes (see screenshots) I personally prefer "character".

### Link this PR to an issue [optional]

Fixes [_#1987_](https://github.com/getAlby/lightning-browser-extension/issues/1987)

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]

Bildschirmfoto 2023-01-18 um 08 06 27
Bildschirmfoto 2023-01-18 um 08 07 28

### How has this been tested?

Tested manually by running extension.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by lujakob** [comment]
@reneaaron this would be a PR for the avvvatars package. Two options regarding the styles. What do you think?

**Comment by reneaaron** [comment]
Great, I just played around a bit with this PR. 👌Currently there seems to be a problem with the layout for longer account names: (the images seems to be squeezed)

image

I personally like the second option better as the initials (at least for how I use the account names) tend to overlap and are often not the best abbreviations. (Multiple LNBits wallets with the same first two characters "LN")

What do you think about adding those avatars to the account list as well? I think they are way better than the generic "wallet" icon currently:
image



Unrelated to that:
Since you derive the avatar from the name, this could possibly even lead to a nice effect on the account settings page (where the avatar is updated as you type the account name).

**Comment by lujakob** [comment]
> Great, I just played around a bit with this PR. 👌Currently there seems to be a problem with the layout for longer account names: (the images seems to be squeezed)
> 
> image
> 
> I personally like the second option better as the initials (at least for how I use the account names) tend to overlap and are often not the best abbreviations. (Multiple LNBits wallets with the same first two characters "LN")
> 
> What do you think about adding those avatars to the account list as well? I think they are way better than the generic "wallet" icon currently: image
> 
> Unrelated to that: Since you derive the avatar from the name, this could possibly even lead to a nice effect on the account settings page (where the avatar is updated as you type the account name).

Good catch. I updated by adding "shrink-0". Nitpick: I replaced the p tag with div, since it's semantically more correct, right?
Also added the avatar to the account screen as you suggested. Also like it.

Anything else?

**Comment by reneaaron** [comment]
Looks great. 🚀

We're currently in the process of finishing up #1964. After we've merged it (which should be in the next few days) we could add the avatars to the accounts detail page as well. 

Other than that I think it's fine for now!

**Review by escapedcat — APPROVED** [review]
ack

**Review by bumi — APPROVED** [review]
utACK
I think we can merge this one and then add the same also on the accounts page once that is merged?

**Pull request merged**
