### PR TITLE
fix: support twitter mobile urls

### LINKED ISSUE #1661: [BUG] Alby should recognize twitter url that start with mobile
### Describe the bug

For some unknown reason when I was browsing twitter on my PC I see that the URL twitter had a mobile word on it: https://mobile.twitter.com/bitdov
So I couldn't see the Alby blue icon to send sats on a profile with lightning address.

### Steps To Reproduce

1. Go to: https://mobile.twitter.com/bitdov
2. Try to send sats to this profile clicking on Alby blue icon

### Expected behavior

See the Alby blue icon to send sats

### Alby information

Alby version: 1.18

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Supports twitter URLs that start with `mobile.`, i.e. https://mobile.twitter.com/bumi

### Link this PR to an issue [optional]

Fixes #1661

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)
- `feat`: New feature (non-breaking change which adds functionality)

### How has this been tested?

Here: https://mobile.twitter.com/bumi

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by escapedcat** [comment]
Should this work?:
image

**Comment by im-adithya** [comment]
Yes, that should

**Review by escapedcat — APPROVED** [review]
ack

Sometimes I need to reload the extension hard, sometimes I do not... In this case I had to reload hard :P Thanks!

**Comment by im-adithya** [comment]
For all battery related fixes, I usually have to click that refresh button in `Extensions`

**Comment by escapedcat** [comment]
Thanks, yes, makes sense

**Pull request merged**
