### PR TITLE
feat: listed https://blogstack.io and https://notebin.org Nostr services on Discover page

### LINKED ISSUE #2066: [Feature] List https://blogstack.io and https://notebin.org Nostr services on Discover page
### Feature description

[Feature] List https://blogstack.io and https://notebin.org Nostr services on Discover page

### Describe the solution

[Feature] List https://blogstack.io and https://notebin.org Nostr services on Discover page

### Describe alternatives

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by ShivamJhaa**
### Describe the changes you have made in this PR

_A clear and concise description of what you want to happen_

### Link this PR to an issue [optional]

Fixes #2066 

### Type of change

(Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]
Screenshot from 2023-02-08 21-51-21

_Add screenshots to make your changes easier to understand. You can also add a video here._

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by ShivamJhaa** [comment]
@escapedcat, @im-adithya Please review the PR, thanks!

**Comment by bumi** [comment]
are those images already compressed and @jankoegel approved :D

**Comment by escapedcat** [comment]
> are those images already compressed and @jankoegel approved :D

Used ImageOptim on them at least :P

**Comment by bumi** [comment]
thanks!

**Pull request merged**
