### PR TITLE
feat: extend webln sendPayment method

### PR DESCRIPTION
**Pull request by pavanjoshi914**
### Describe the changes you have made in this PR

1. add metadata as an optional parameter to the  ```SendPayment``` function

2. code works when metadata is passed or not passed

### How has this been tested?
Tested by making payments with and without passing metadata from the client-side using prototype

image

### Checklist

- [X] My code follows the style guidelines of this project and performed a self-review of my own code
- [X] New and existing tests pass locally with my changes
- [X] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
@bumi ?

**Comment by bumi** [comment]
I think we need to propose this change to the webln spec, ideally other webln wallets will also implement that.
So I think a first step is to write a proposal to the spec for this. This means need to explain the idea and reason for this and also specify what can be used as metadata. 
Did you already write something on this?

**Comment by pavanjoshi914** [comment]
> s means need to explain th

https://gist.github.com/pavanjoshi914/53f28f9d40ed3bc9f3028a2117a417a4 
If this looks good to you! I can finalize and upload this as a new spec-proposal for webln

**Comment by pavanjoshi914** [comment]
@bumi  can you review that gist?

**Comment by pavanjoshi914** [comment]
@bumi

**Pull request merged**
