### PR TITLE
feat: responsive account settings + settings page

### PR DESCRIPTION
**Pull request by pavanjoshi914**
### Describe the changes you have made in this PR

make settings page responsive

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Checklist

- [X] Self-review of changed code
- [X] Manual testing
- [X] Added automated tests where applicable
- [X] Update Docs & Guides
- For UI-related changes
- [X] Darkmode
- [X] Responsive layout

### CODE REVIEW

**Comment by reneaaron** [comment]
Before:
image

After:
image

IMO this is worse than it was before, as there is no visual rhythm, missing spacing between elements, inconsistent alignment of text, etc.

**Comment by pavanjoshi914** [comment]
image
this pr was for the account settings page and not the settings page. as we use refactored component it breaked settings page checking it

**Comment by pavanjoshi914** [comment]
@reneaaron i corrected settings page in the same pr

**Comment by pavanjoshi914** [comment]
image
 
 + added new property to keep few settings inline on smaller screens such as toggles

**Review by reneaaron — APPROVED** [review]
tACK

**Pull request merged**
