### PR TITLE
fix: accounts info connector race condition

### LINKED ISSUE #2327: [BUG] development mode Polar LND node connect fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Connecting the extension with a Polar LND node locally causes an error. The `getBalance` request fails with status `ERR_CERT_AUTHORITY_INVALID`

I investigated and found the `getInfo` request fails. It seems like a race condition problem, as the failing `getChannel` is first in the network panel, the succeeding `getInfo` is second.

I removed the Promise.all and it fixes the problem.

### Screenshots [optional]

Bildschirmfoto 2023-04-09 um 09 03 06

### Steps To Reproduce

connect to LND node with Polar locally

### Expected behavior

It should work.

### Alby information

latest master

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

Fix Polar LND node connection request race condition resulting in connector error

### Link this PR to an issue [optional]

Fixes #2327

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]

_Add screenshots to make your changes easier to understand. You can also add a video here._

### How has this been tested?

Manually

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by rolznz** [comment]
@lujakob I feel like this does not fix the root cause, but I also don't know why there would be a race condition. Isn't this just two standard `fetch` API calls?

**Comment by lujakob** [comment]
> @lujakob I feel like this does not fix the root cause, but I also don't know why there would be a race condition. Isn't this just two standard `fetch` API calls?

They should just work yes. They do if I request them independently via Postman. But I have no clue what the exact issue is. Maybe it for some reason is sending them at the exact same time with `Promise.all` Maybe some Chrome browser internals with local SSL sending two requests at the same time - I have no clue.

**Comment by lujakob** [comment]
@rolznz do you also you Polar to connect to an LND connector? I really wonder why only I have this problem?! Or do you know any devs who use Polar? I would suppose most here...

**Comment by rolznz** [comment]
@lujakob mostly I use the Alby regtest environment (https://github.com/getAlby/lightning-browser-extension/wiki/Test-setup) for testing unless I have a specific need to setup a local network using Polar

**Review by bumi — APPROVED** [review]
This loads the data probably a bit slower (no longer in parallel)
but less parallel is probably also good.

**Comment by reneaaron** [comment]
I feel like this just fixes some symptoms (but not the root cause). Why would parallel requests be a problem?

**Comment by bumi** [comment]
then let's leave it and it has to somehow work.

**Pull request closed without merging**
