### PR TITLE
Added Music Side Project and CurioCaster  to the "Discover" page

### PR DESCRIPTION
**Pull request by AdarshRawat1**
### Describe the changes you have made in this PR
Added https://musicsideproject.com/ and https://curiocaster.com/  to the "Discover" page under entertainment section. 

### Link this PR to an issue [optional]

Fixes _ #2353 by @MoritzKa 

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]
Current Discover Page -
image

Updated Discover Page- 
image

### Note

I have not yet uploaded the logos to the Content Delivery Network (CDN). Currently, I am using GitHub links. Could you please assist me with uploading them to the CDN as I am not familiar with the process?

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by MoritzKa** [comment]
https://cdn.getalby-assets.com/alby-extension-website-screen/curiocaster_thumbnail.png
https://cdn.getalby-assets.com/alby-extension-website-screen/musicsideproject_thumbnail.png

**Comment by AdarshRawat1** [comment]
@MoritzKa  I have updated the links. Please review the changes. 
Do you think the resolution of the Music Side Project logo needs to be adjusted?
Screenshot -
image

**Comment by reneaaron** [comment]
> now why the thumbnail is cut off?
> It appears a bit blurry here on GitHub.

It's because the images are supposed to be squares. (it's 330x300)

**Comment by jankoegel** [comment]
> @jankoegel do you know why the thumbnail is cut off? It appears a bit blurry here on GitHub. compared to the original file:

here's the image converted to a square (333x333px) and compressed:
musicsideproject_thumbnail_2

**Comment by AdarshRawat1** [comment]
> > @jankoegel do you know why the thumbnail is cut off? It appears a bit blurry here on GitHub. compared to the original file:
> 
> here's the image converted to a square (333x333px) and compressed: musicsideproject_thumbnail_2

Thank you 

> > @jankoegel do you know why the thumbnail is cut off? It appears a bit blurry here on GitHub. compared to the original file:
> 
> here's the image converted to a square (333x333px) and compressed: musicsideproject_thumbnail_2

Thank you @jankoegel , I think this is good enough. Please upload this logo to CDN.

image

**Comment by MoritzKa** [comment]
Thanks a lot, guys!!!

**Comment by AdarshRawat1** [comment]
> 

@MoritzKa Kindly add this logo to CDN and provide the link.

**Comment by AdarshRawat1** [comment]
> > @jankoegel do you know why the thumbnail is cut off? It appears a bit blurry here on GitHub. compared to the original file:
> 
> here's the image converted to a square (333x333px) and compressed: musicsideproject_thumbnail_2

@MoritzKa  Kindly add this logo to CDN and provide the link.

**Comment by AdarshRawat1** [comment]
> https://cdn.getalby-assets.com/alby-extension-website-screen/curiocaster_thumbnail.png https://cdn.getalby-assets.com/alby-extension-website-screen/musicsideproject_thumbnail.png

@reneaaron @MoritzKa, please update the logo of "music side project" on CDN.

**Comment by reneaaron** [comment]
tACK

**Pull request merged**
