### PR TITLE
Added note to SETUP.md

### PR DESCRIPTION
**Pull request by eesazahed**
### Describe the changes you have made in this PR

I added a note to the top of SETUP.md. The note informs the reader that while the tutorial uses Yarn as the package manager, they can substitute it with other preferred managers like npm or pnpm, and should also update the package.json file accordingly.

### Type of change

- `docs`: Documentation update

### How has this been tested?

Tested locally with successful results.

### Checklist

- [ ] Self-review of changed code
- [ ] Manual testing
- [ ] Added automated tests where applicable
- [ x] Update Docs & Guides
- For UI-related changes
- [ ] Darkmode
- [ ] Responsive layout

### CODE REVIEW

**Comment by reneaaron** [comment]
I am not sure this PR is actually solving a problem: 

If you are using this repository for the first time (and you have no knowledge about other package managers) you should probably stick with yarn. If you are already using other package managers I suppose you should also know how to use your preferred package manager instead. 

> Just be sure to make the same changes in your local `package.json` file while in development.

I also don't understand this hint. Yarn & npm both use package.json?

**Comment by eesazahed** [comment]
So the problem I am trying to solve is that some new/inexperienced devs might not use yarn. They might only have npm installed. So I added that note at the top.

> I also don't understand this hint. Yarn & npm both use package.json?

In package.json, you can see `"build": "yarn build:chrome && yarn build:firefox && yarn build:opera",`

The note is to remind the reader that they can change it to `"build": "npm build:chrome && npm build:firefox && npm build:opera"` in addition to all of the other use cases of yarn in the file.

**Comment by reneaaron** [comment]
I think unexperienced devs should just install yarn instead of manually editing the package.json file:

`npm install --global yarn`

**Comment by eesazahed** [comment]
I get what you're saying. Final decision is up to you

**Comment by pavanjoshi914** [comment]
I think the current version of documentation is consistent with yarn. and its not a greater side of usecase for anyone to suggest alternate package manager in docs. closing this

**Pull request closed without merging**
