### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by secondl1ght**
### Describe the changes you have made in this PR

Update manifest version.

### Link this PR to an issue

#1051 

### Type of change (Remove other not matching type)

- `docs`: Documentation update

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by secondl1ght** [comment]
`npx playwright test` is failing here on GitHub but I ran it locally and all the tests passed - looks like it is timing out here.

**Comment by bumi** [comment]
careful: afaik v3 defines a completely different architecture of the extension. 
there is no background-script anymore, but it introduces service-workers. 

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by bumi** [comment]
actually let's close this one. because it will be open for long and changing the number will be easily done when we know what exactly needs to be done. 

did you actually run and use Alby with this change?

**Comment by secondl1ght** [comment]
Sounds good - thanks for the heads up, yes I ran it locally and it appeared to be working (no errors in browser console or backpage console). I didn't run through all the functionality though.

**Pull request closed without merging**
