### PR TITLE
chore: unify connector functions

### LINKED ISSUE #1712: Unify connector interface
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The connector functions either return the response or throw an error. 
Except `connectPeer` and `getInvoices` those return an error. 

I think we should have this unified. @escapedcat why do you not throw an error in those functions like in the other functions? 

https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/connectors/connector.interface.ts#L120-L122

### Screenshots [optional]

_No response_

### Steps To Reproduce

..

### Expected behavior

unify all the things

### Alby information

...

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

_No response_

### PR DESCRIPTION
**Pull request by bumi**
We throw an error on the error case

### Link this PR to an issue [optional]

fixes #1712 

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

needs testing

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]
Thanks! This makes a lot of sence

**Comment by escapedcat** [comment]
Uhm, at one point in time the returned Error was used to trigger and show an error-toast. But this doesn't seem to work anymore (on master) so this change makes the current state better.  
Not sure if we should to let the user know that their connector doesn't support this via a toast.

**Comment by bumi** [comment]
I don't fully get your last comment. what's the suggestion?

**Comment by escapedcat** [comment]
No suggestion. Your PR improves the current situation. This is good.

Question:  
At one point in time the returned Error was used to trigger a toast within the extension to give the user feedback.  
Currently the user doesn't get any feedback in the UI, right? Do we want to give feedback?

**Comment by bumi** [comment]
why does the user not get feedback? 

https://github.com/getAlby/lightning-browser-extension/pull/1713/files#diff-d07eb0245fd06ccaf878d056614cc4a944a918bbdd4267619cf3eb264bdd7eb3 -> here for example: both return error: message in the error case.

**Comment by escapedcat** [comment]
image
Might a bug then? I don't see anything inside the UI currently.

**Comment by bumi** [comment]
hmm. your error is strange. because getInvoices should be implemented on Lndhub

**Comment by escapedcat** [comment]
> hmm. your error is strange. because getInvoices should be implemented on Lndhub

All good, that was just a test by replacing the function

**Comment by bumi** [comment]
hmmm. doesn't seem we do this? https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/DefaultView/index.tsx#L133-L138

**Comment by escapedcat** [comment]
When #1080 was merged it looked like this:

But now that we support most of the important connectors we're good.

**Comment by bumi** [comment]
naja, can you explain that? that PR is from Jul 26. so I don't know what you try to say. 
is this related to this PR? 

> But now that we support most of the important connectors we're good.
we still don't support it in all. and if we broke something we should not say 🤷 we do most ...

**Comment by escapedcat** [comment]
:D So, this is related to this PR because by looking at this I noticed that apparently "showing the toast to the user" does not work anymore. We need to decide we want to show something to the user if their connector doesn't support this yet.

- If yes, close this PR and we open an issue to fix the toast
- If no, merge this PR and keep it the current way

It's a decision of priorization

**Comment by bumi** [comment]
this seems broken in master, no idea when/how it got broken (that could use investigation, because I have no idea how it could have worked before) 

this PR actually fixes this I think for the invoices. at least it should. https://github.com/getAlby/lightning-browser-extension/pull/1713/files#diff-167ef8f8c43cebe91d5e71f3724e953a69277ab2c9b30af8dfc47a0707613544

what do we need to prioritize?

**Review by escapedcat — APPROVED** [review]

**Pull request merged**
