### PR TITLE
Added Iris.to

### LINKED ISSUE #2087: [Feature] Add https://iris.to/ client on Nostr discovery page
### Feature description

Add (https://iris.to/) client on Nostr discovery page

### Describe the solution

Add (https://iris.to/) client on Nostr discovery page

### Describe alternatives

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by MoritzKa**
### Describe the changes you have made in this PR

Added Iris.to to Discover page

### Link this PR to an issue [optional]

Fixes #2087

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)
- `feat`: New feature (non-breaking change which adds functionality)
- `feat!`: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- `docs`: Documentation update

### Screenshots of the changes [optional]

_Add screenshots to make your changes easier to understand. You can also add a video here._

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [ ] My code follows the style guidelines of this project and performed a self-review of my own code
- [ ] New and existing tests pass locally with my changes
- [ ] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by MoritzKa** [comment]
image

**Comment by MoritzKa** [comment]
no need to merge unless we want apps without lightning.

**Review by reneaaron — APPROVED** [review]
utACK

**Comment by bumi** [comment]
thanks, is the image properly compressed?

**Pull request merged**
