### PR TITLE
fix: update citadel sdk for core lightning support

### PR DESCRIPTION
**Pull request by AaronDewes**
#### Type of change (Remove other not matching type)

- Bug fix (non-breaking change which fixes an issue)

#### Describe the changes you have made in this PR -

This updates the Citadel SDK and makes a minor change that is required to support Core Lightning (previously called c-lightning) on Citadel in the future.

#### How Has This Been Tested?

I manually ensured everything was still working correctly when connected to my local Citadel.

#### Checklist:

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by bumi** [comment]
utACK. 

in your the sdk code the `MiddlewareLND` now works for both lnd and cln? 

(btw. slightly related thread: https://twitter.com/EricSirion/status/1509906940767481859 )

**Review by bumi — APPROVED** [review]

**Comment by escapedcat** [comment]
@AaronDewes would you mind having a look at this?: https://github.com/getAlby/lightning-browser-extension/pull/747   
For some reason the jest setup has issues with the citadel-import. Maybe you have an idea what needs to be changed. If not no worries.

**Comment by AaronDewes** [comment]
>  in your the sdk code the MiddlewareLND now works for both lnd and cln?

Yes, only the name is a leftover.

**Comment by AaronDewes** [comment]
> @AaronDewes would you mind having a look at this?: #747 For some reason the jest setup has issues with the citadel-import. Maybe you have an idea what needs to be changed. If not no worries.

It seems to be because we use ESM in @runcitadel/sdk, but Alby doesn't use it otherwise

**Comment by bumi** [comment]
@escapedcat #747 is independent of this, correct? 
so we can merge this one?

**Comment by escapedcat** [comment]
> @escapedcat https://github.com/getAlby/lightning-browser-extension/pull/747 is independent of this, correct?
so we can merge this one?

Yup, all good here

**Pull request merged**
