### PR TITLE
feat: handle invalid invoices

### LINKED ISSUE #547: Handle invalid lightning addresses
Currently when I enter an invalid lightning address into the Send input, Alby will crash with no indication of what happened. Maybe we should have a message appear saying something like 'invalid lightning address'?

### PR DESCRIPTION
**Pull request by dylancom**
Fixes #547

### CODE REVIEW

**Comment by bumi** [comment]
@secondl1ght can you test this?

**Comment by secondl1ght** [comment]
What is the expected behavior for this? Right now when I enter 'secondl1ght@getalby.comm' I do not get an error message, but I think we are supposed to get an error for this right?

**Comment by secondl1ght** [comment]
When I enter 'asdfkjhsdf' it does give an error though which is good.

**Comment by dylancom** [comment]
Now it also gives an error message on: secondl1ght@getalby.comm

**Comment by secondl1ght** [comment]
Ok I tested this and it's working now.

**Pull request merged**
