### PR TITLE
feat: show fiat in Confirm Payment

### PR DESCRIPTION
**Pull request by lisabaut**
### Describe the changes you have made in this PR

This PR renders the Fiat Amount of a confirmable payment (if the setting "showFiat" is true and fiatAmount exists accordingly).

~Design came from https://github.com/getAlby/lightning-browser-extension/issues/1306#issuecomment-1222261734~
=> Design changed, see Screenshot and comments below

### Link this PR to an issue

Closes https://github.com/getAlby/lightning-browser-extension/issues/1306

### Type of change (Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes (If any)

Bildschirmfoto 2022-08-24 um 10 27 26

### How has this been tested?
usign Stackernews and invoke payments

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]
Should we add a simple render test for `PaymentSummary`?

**Comment by bumi** [comment]
I'd actually would just ad this inline

```
Amount
<strong?>123 sats<strong> (~2.32USD)
```

now we need much more space and more content is below the fold and people need to know what fiat is.

**Comment by lisabaut** [comment]
> Should we add a simple render test for `PaymentSummary`?

Test is added

**Comment by lisabaut** [comment]
> I'd actually would just ad this inline
> 
> ```
> Amount
> <strong?>123 sats<strong> (~2.32USD)
> ```
> 
> now we need much more space and more content is below the fold and people need to know what fiat is.

See updated code and screenshot

**Pull request merged**
