### PR TITLE
Refactor/axios

### PR DESCRIPTION
**Pull request by escapedcat**
prepare vor MV3
- use fetch adapter for axios

TODO:

- ~fix unit-tests~

Context:  
- Axios' default adpater doesn't work in SW. Switching to a fetch-adapter we can keep the advantages of Axios
- Currently this adpater only work in Axios v0.x not in v1.x
- I'll keep checking the reo and also the new upcoming "official" fetch adapter PR.

### CODE REVIEW

**Comment by bumi** [comment]
can we make a PR also with the axios fetch adapter PR? (and thus also show what fails in that PR?
as this seems to get into axios it seems to me a bit more promising?

**Comment by escapedcat** [comment]
> can we make a PR also with the axios fetch adapter PR? (and thus also show what fails in that PR? as this seems to get into axios it seems to me a bit more promising?

Can do but to unblock MV3 can we merge this first?

**Comment by bumi** [comment]
hm, no need to close this, just because I think it is worth exploring that official(?) axios PR.

**Comment by bumi** [comment]
I thought that's an alternative to it?

**Comment by escapedcat** [comment]
> I thought that's an alternative to it?

It would be if the Axios one would be merged & released. For now we're better with this approach, I think. At least this works.

**Comment by bumi** [comment]
the PR sounded promising to me. The maintainer said it looks good and it was actively worked on.

**Comment by escapedcat** [comment]
> the PR sounded promising to me. The maintainer said it looks good and it was actively worked on.

Sure but it isn't ready and it not related to this PR. Or do you want to switch to that fork in this PR here? Not sure what your expectation is I guess.

**Comment by bumi** [comment]
Why is it not related to this PR? This PR changes axios to use a fetch adapter by adding another dependency. 
An alternative to this is to use the branch from axios which has support signaled to get merged. 
so it's the same just the axios branch seems to become the official way of doing this.
(maybe you want to help me with my replit to show how it is used and then we can also help getting this in the offical axios lib?)

**Comment by escapedcat** [comment]
Findings here: https://github.com/getAlby/lightning-browser-extension/pull/1825  
It might work if we use a build version of the forked branch. Not sure.

So far I would go with this PR in the current state and switch to the "official" axios adapter as soon as it's merged.

**Comment by im-adithya** [comment]
Closing this as we use fetchAdapter

**Pull request closed without merging**
