### PR TITLE
Updated extension icons

### PR DESCRIPTION
**Pull request by GBKS**
Based on the discussion in #793.

- Updated sleeping, yellow, and blue icons
- Added green variation
- Added dark theme variations
- Removed unnecessary SVG size variations (SVGs scale, one file is enough)

Icons should now be consistent. The old variations had slight differences in size, line thickness, etc.

Note that the new blue icons has the regular Alby eyes, instead of the four vertical lines indicating it being busy. How does that look?

Please take a look, try it out, and let me know what needs to be adjusted.

### CODE REVIEW

**Comment by escapedcat** [comment]
Check out this branch, built it and added it to chrome.  
I somehow expected the icon to change in color. But so far I only see the yellow off/on version.  
You described [the different states here](https://github.com/getAlby/lightning-browser-extension/issues/793#issuecomment-1110732697). Are these implemented? Or is this PR only adding the icons but the functionality is missing so far?

> Please take a look, try it out, and let me know what needs to be adjusted.

I feel like I'm missing something or I don't know how to test this. Can you help?

**Comment by escapedcat** [comment]
Check out this branch, built it and added it to chrome.  
I somehow expected the icon to change in color. But so far I only see the yellow off/on version.  
You described [the different states here](https://github.com/getAlby/lightning-browser-extension/issues/793#issuecomment-1110732697). Are these implemented? Or is this PR only adding the icons but the functionality is missing so far?

> Please take a look, try it out, and let me know what needs to be adjusted.

I feel like I'm missing something or I don't know how to test this. Can you help?

**Comment by GBKS** [comment]
@escapedcat sorry, was not super clear. I only added/updated icons, but did not implement any code changes to support different states. I have no clue where I'd even start implementing new states.

As far as testing, it would be helpful to review that I didn't delete any needed icon files, that all sizes are there that we need, double-checking that the visuals are all consistent, and that the states that are implemented look good in the browser.

Also, the Figma file for the icons is [here](https://www.figma.com/file/YVMGfhSHNkK7IWWkCeGUvp/%E2%9A%AB%EF%B8%8FAlby?node-id=901%3A10662).

**Comment by escapedcat** [comment]
Got it, thanks! Let's see how we continue with this then.

**Comment by reneaaron** [comment]
@escapedcat I am currently implementing the new icons and will probably create a new PR based on Christoph's work. 👍

**Comment by escapedcat** [comment]
Thanks! Closing in favour of #1086

**Pull request closed without merging**
