### PR TITLE
feat: add btcmap to the website directory

### PR DESCRIPTION
**Pull request by secondl1ght**
### Describe the changes you have made in this PR
I added the new website [BTC Map](https://btcmap.org) to the Websites directory under the Shopping category. BTC Map has just launched a lightning tipping feature for map contributors and there will be more lightning integration in the future that will be compatible with Alby users.

I noticed that for the other logo assets on this page you are using an Alby CDN to serve the images. I have included a URL to the BTC Map logo which can be left as-is or can be downloaded and added to the asset server with the others.

Thanks!! 🙂 

### Type of change
- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]
image

### How has this been tested?
I ran this locally.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — COMMENTED** [review]
lgtm, @bumi how to add the svg to the alby-assets?

**Comment by MoritzKa** [comment]
> lgtm, @bumi how to add the svg to the alby-assets?

DM

**Comment by MoritzKa** [comment]
The intention of the Websites screen in Alby is to provide an easy access to WebLN apps. Lightning Network Stores has no WebLN functionality but helps to spread bitcoin spending. The same does BTC Map. But I hope to see WebLN functionality there soon :)
What are your plans in this regard, @secondl1ght ?

**Comment by secondl1ght** [comment]
> The intention of the Websites screen in Alby is to provide an easy access to WebLN apps. Lightning Network Stores has no WebLN functionality but helps to spread bitcoin spending. The same does BTC Map. But I hope to see WebLN functionality there soon :) What are your plans in this regard, @secondl1ght ?

We just added some WebLN functionality on the site actually, you can now tip map contributors with sats. See screenshot below:

image

There will be other places you can tip these users in the future like on the leaderboard and on their profiles. There is potentially some options for lightning integration on the map itself too in the future as well as for the communities pages we plan to build out.

Lots of plans!!

**Comment by MoritzKa** [comment]
Sounds great. Let´s merge it.

**Comment by escapedcat** [comment]
@secondl1ght you can use this now:
https://cdn.getalby-assets.com/alby-extension-website-screen/btcmap-logo.svg

**Comment by secondl1ght** [comment]
@escapedcat awesome thanks! This is complete now.

**Review by escapedcat — APPROVED** [review]

**Pull request merged**
