### PR TITLE
feat: new toasts 🔥🍞

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

[Screencast from 2023-09-06 15:10:23.webm](https://github.com/getAlby/lightning-browser-extension/assets/100827540/9ae00f64-1c4b-41af-8411-513ef0171d11)

### CODE REVIEW

**Comment by bumi** [comment]
Will the bottom always be well visible? on a bigger screen when I enter something at the top?

**Comment by rolznz** [comment]
How does the user close the toast right now? do we want/need that?

**Review by rolznz — APPROVED** [review]

**Comment by reneaaron** [comment]
> Will the bottom always be well visible? on a bigger screen when I enter something at the top?

It's a fixed container, so yes.

> How does the user close the toast right now? do we want/need that?

They can't currently, the automatically go away after 4s (success) / 8s (error) unless there is a different duration defined. We could easily add that though...

**Comment by reneaaron** [comment]
I've added a close icon for toasts that show longer than 10s. :+1:

**Pull request merged**
