### PR TITLE
feat: add allowance screen send link

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

Add "Send" button/link to popup Allowance View to spare one user click to send a payment. Optionally preset invoice field value from clipboard.

### Link this PR to an issue [optional]

Fixes 2812

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)
- `feat`: New feature (non-breaking change which adds functionality)
- `feat!`: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- `docs`: Documentation update

### Screenshots of the changes [optional]

_Add screenshots to make your changes easier to understand. You can also add a video here._

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [ ] Self-review of changed code
- [ ] Manual testing
- [ ] Added automated tests where applicable
- [ ] Update Docs & Guides
- For UI-related changes
- [ ] Darkmode
- [ ] Responsive layout

### CODE REVIEW

**Comment by lujakob** [comment]
@stackingsaunter I would welcome your opinion about the link/button. @bitcoinuser suggested a button at the bottom of the screen, but I think the bottom part is reserved for the "Recent transactions" list. I would suggest to place it underneath the website image box (or even the Hyperlink "Send a budget for one-click payments") - a button could be more prominent, but takes a lot of space, so maybe a Hyperlink as well? (clicking the link navigates to the send screen, same as arrow back at the top left)


Bildschirmfoto 2023-10-14 um 11 07 31

**Comment by lujakob** [comment]
Anyone knows why a `navigator.clipboard.readText()` call throws an exception?

`DOMException: Document is not focused.
code: 0
message: "Document is not focused."
name: "NotAllowedError"`

clipboard-read permissions are set as far as I can see. I test calling this function delayed and see the field is focused, so it should work.

Maybe @rolznz @reneaaron got an idea?

**Comment by lujakob** [comment]
TBH I'm not sure if we want to automatically paste an address anyways, because it is less explicit. Dealing with payments and addresses is very delicate. Am I really sure this is the right address I want to pay and not another address I copied just seconds before. I'm not sure if this might confuse or lead to unexpected behaviour. What do you guys think? Safe to apply automatic clipboard paste?

**Comment by rolznz** [comment]
I think actually the allowance view should not require the user to go "back" to the home page in order to send a payment. Could it just be a small section at the top of the popup but still on the home page, so the user can scroll down to see the normal actions? then we do not need to add send/receive/etc buttons here too.

For automatic paste, I think @bumi had some hesitations about this. Even if we try to make sure we only paste values that are relevant by using a regex, access to the clipboard without a user action may be a bit unsafe?

**Comment by rolznz** [comment]
@reneaaron @stackingsaunter  I feel like being able to see the current site's transaction history is less important, what do you think?

**Comment by stackingsaunter** [comment]
We talked about this today with @reneaaron but there's one problem, that any Send button placed on this screen leaves an impression like you're about to send a payment to this website (little bit like in battery payment to Bumi above). So I'd actually not show Send button on this screen at all.

Another approach would be something like this: 


image

By default we show main popup screen with a box indicating where we are connected. Then by clicking it we enter website screen. Thoughts? @reneaaron @rolznz

**Comment by stackingsaunter** [comment]
I think this could be closed in favour of https://github.com/getAlby/lightning-browser-extension/issues/1568#issuecomment-2000028368 ? cc @reneaaron

**Pull request closed without merging**
