### PR TITLE
Upgrade to Tailwind v3

### LINKED ISSUE #491: Update to Tailwind 3
There has been a major release of Tailwind. 
We need to update to the latest version - see the [upgrade guide](https://tailwindcss.com/docs/upgrade-guide)

depfu PR: https://github.com/getAlby/lightning-browser-extension/pull/484

### PR DESCRIPTION
**Pull request by secondl1ght**
I have upgraded `tailwindcss@latest postcss@latest autoprefixer@latest @tailwindcss/forms@latest` using Yarn, the guide says to use npm but I think it should work the same. 

The only additional step we had to take for our project was to remove `mode: "jit"` from the tailwind.config.js file. I went through the whole project to search for any instances of breaking changes but we were not using any of these features in v2.

All in all it was a pretty easy upgrade especially with the nice guide that Tailwind released.

I wasn't sure if you just wanted to merge the dependabot PR or I should make one, but the bot one doesn't include the `autoprefixer@latest` upgrade which was recommended in the guide. It also doesn't include the update to the tailwind config file.

It will be good to be on the latest release though, I am becoming a big fan of Tailwind!

Closes #491

### CODE REVIEW

**Comment by dylancom** [comment]
Is storybook still working properly? I believe I added jit mode to support modern stuff in Storybook.

**Comment by secondl1ght** [comment]
I have never actually tried out storybook before, I tried running it by doing `yarn storybook` with and without the `mode: "jit"` and I couldn't get it running either time. So there must be something else wrong, here is my ouput:

```mk@pop-os:~/Desktop/CODE/dark-merged$ yarn storybook
yarn run v1.22.15
$ start-storybook -p 6006
info @storybook/react v6.4.9
info 
info => Loading presets
info => Using PostCSS preset with postcss@8.4.5
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modules
info => Using cached manager
99% done plugins webpack-hot-middlewarewebpack built preview f2fb055661772743d9af in 5355ms
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js):
Error: /home/mk/Desktop/CODE/dark-merged/.storybook/preview.js-generated-config-entry.js: 'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled).
    at enableFeature (/home/mk/Desktop/CODE/dark-merged/node_modules/@babel/helper-create-class-features-plugin/lib/features.js:51:13)
    at PluginPass.pre (/home/mk/Desktop/CODE/dark-merged/node_modules/@babel/helper-create-class-features-plugin/lib/index.js:78:35)
    at transformFile (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transformation/index.js:94:27)
    at transformFile.next (<anonymous>)
    at run (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transformation/index.js:33:12)
    at run.next (<anonymous>)
    at Function.transform (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:261:32)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:223:11)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:189:28
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/gensync-utils/async.js:73:7
    at /home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:113:33
    at step (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:287:14)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:273:13
    at processResult (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:701:19)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:807:5
    at /home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js:59:103
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js):
Error: /home/mk/Desktop/CODE/dark-merged/generated-stories-entry.js: 'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled).
    at enableFeature (/home/mk/Desktop/CODE/dark-merged/node_modules/@babel/helper-create-class-features-plugin/lib/features.js:51:13)
    at PluginPass.pre (/home/mk/Desktop/CODE/dark-merged/node_modules/@babel/helper-create-class-features-plugin/lib/index.js:78:35)
    at transformFile (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transformation/index.js:94:27)
    at transformFile.next (<anonymous>)
    at run (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transformation/index.js:33:12)
    at run.next (<anonymous>)
    at Function.transform (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:261:32)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:223:11)
    at processResult (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:701:19)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:807:5
    at /home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js:59:103
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js):
Error: /home/mk/Desktop/CODE/dark-merged/storybook-init-framework-entry.js: 'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled).
    at enableFeature (/home/mk/Desktop/CODE/dark-merged/node_modules/@babel/helper-create-class-features-plugin/lib/features.js:51:13)
    at PluginPass.pre (/home/mk/Desktop/CODE/dark-merged/node_modules/@babel/helper-create-class-features-plugin/lib/index.js:78:35)
    at transformFile (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transformation/index.js:94:27)
    at transformFile.next (<anonymous>)
    at run (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transformation/index.js:33:12)
    at run.next (<anonymous>)
    at Function.transform (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:261:32)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/mk/Desktop/CODE/dark-merged/node_modules/gensync/index.js:223:11)
    at processResult (/home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:701:19)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:807:5
    at /home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/mk/Desktop/CODE/dark-merged/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/mk/Desktop/CODE/dark-merged/node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js:59:103

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It referencing babel in the output, I am on the latest master branch, is storybook currently working for you? Maybe I am missing a step?

And yes `focus-visible` is working, there was no mention of breaking changes for this class.

**Review by dylancom — COMMENTED** [review]
Remove dark mode configuration
The dark mode feature is now enabled using the media strategy by default, so you can remove this key entirely from your tailwind.config.js file, unless you’re using the class strategy.

**Comment by dylancom** [comment]
**Configure content sources**
Since Tailwind no longer uses PurgeCSS under the hood, we’ve renamed the purge option to content to better reflect what it’s for:

**Comment by dylancom** [comment]
**Automatic transforms and filters**
In Tailwind CSS v3.0, transform and filter utilities like scale-50 and brightness-75 will automatically take effect without needing to add the transform, filter, or backdrop-filter classes

**Comment by dylancom** [comment]
**flex-grow/shrink**
We’ve added grow-* and shrink-* as aliases for flex-grow-* and flex-shrink-*:
The old class names will always work but you’re encouraged to update to the new ones.

**Comment by secondl1ght** [comment]
I checked that everything was good in the upgrade guide, were you just posting these to let me know or did I miss something? @dylancom

**Comment by dylancom** [comment]
I mentioned those as they advice code changes, but haven't been done yet.

**Comment by secondl1ght** [comment]
> **Remove dark mode configuration** The dark mode feature is now enabled using the media strategy by default, so you can remove this key entirely from your tailwind.config.js file, unless you’re using the class strategy.

This one we do not want to remove because we are utilizing the class strategy for our dark mode.



> **Configure content sources** Since Tailwind no longer uses PurgeCSS under the hood, we’ve renamed the purge option to content to better reflect what it’s for:

It looks like I missed this one somehow.. but I have updated it to say `content` now. Thanks!



> **Automatic transforms and filters** In Tailwind CSS v3.0, transform and filter utilities like scale-50 and brightness-75 will automatically take effect without needing to add the transform, filter, or backdrop-filter classes

For this one I searched the whole project for any instances of the `transform` `filter` or `backdrop-filter` classes but couldn't find any, so I think we are good here?



> **flex-grow/shrink** We’ve added grow-* and shrink-* as aliases for flex-grow-* and flex-shrink-*: The old class names will always work but you’re encouraged to update to the new ones.

I did a search for these as well back when I did this PR and thought there was nothing, now I see there were some `flex-shrink` classes used so I have switched those to `shrink` now.

Thanks for reviewing this @dylancom

**Comment by dylancom** [comment]
The class strategy refers to manually activating class="dark" on the html tag. We rely on the prefered color scheme right?
https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

We have different places where "transform" is used, in combo with opacity, rotation, scaling

**Comment by secondl1ght** [comment]
So you are right about the dark mode. When I initially read it I thought they meant the `dark:` classes on the elements themselves. I have updated that now and also removed all the instances of the `transform` class. Sorry for not catching these things myself, I think the reason is that I've been busy trying to do 2 jobs, but soon I will have left my fiat job to focus on bitcoin dev full-time so I will be able to work on this with no distractions.

**Review by dylancom — APPROVED** [review]

**Pull request merged**
