### PR TITLE
fix: back button functionality in receive screen

### LINKED ISSUE #1542: Clicking on back button should go to the previous window
### Describe the bug

Generate an invoice and click back button, should go to previous window and not to home window.

### Screenshots

https://user-images.githubusercontent.com/1178856/192901751-4bda697f-9692-4b34-8ed9-4f3b3df08aa7.mp4

### To Reproduce

1. Click on receive button
2. Generate an invoice
3. Click on back button

### Expected behavior

Not go to home window but to the previous window

### Alby information

- Alby Version: 1.16.1

### PR DESCRIPTION
**Pull request by manavdesai27**
### Describe the changes you have made in this PR

Changed back button functionality to go back to previous screen rather than home in receive screen.

### Link this PR to an issue [optional]

Fixes #1542 

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]

https://user-images.githubusercontent.com/74018438/218330325-13b58007-ecb3-41a9-8d72-e782b9d79e18.mp4

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by escapedcat** [comment]
"back" from the receive screen doesn't work anymore, does it?

**Comment by im-adithya** [comment]
Can you please do a rebase and DRY up the code, we use the same thing in #2094

**Comment by im-adithya** [comment]
> back" from the receive screen doesn't work anymore, does it?

It works, but takes it to home screen to avoid setting everything to defaults again (but now we are anyways doing it for #2094)

**Comment by escapedcat** [comment]
Does it?

https://user-images.githubusercontent.com/1016218/218465380-402b8cf7-9a10-4349-b582-de6399225804.mov

**Comment by im-adithya** [comment]
That's weird!
Can you check the logs? It works fine for me!

**Comment by escapedcat** [comment]
Logs are empty 🤷‍♂️   
@manavdesai27 maybe just double check. If it's fine for both of you we're good I guess.

**Comment by im-adithya** [comment]
> Logs are empty 🤷‍♂️

Hmmm 🤔 maybe because of the mv3 stuff?

**Comment by manavdesai27** [comment]
> Can you please do a rebase and DRY up the code, we use the same thing in #2094

Will do!

**Comment by manavdesai27** [comment]
> Logs are empty man_shrugging @manavdesai27 maybe just double check. If it's fine for both of you we're good I guess.

Let me check

**Comment by manavdesai27** [comment]
@im-adithya My origin and local branches have diverged. How do I fix it?

**Comment by manavdesai27** [comment]
Once it is on the amount and description screen, it doesn't navigate back. Gotta find a workaround for it.

**Comment by im-adithya** [comment]
> "back" from the receive screen doesn't work anymore, does it?

Ahhh, I thought you were talking about master, I wasn't testing this PR

Sorry for the confusion!

**Comment by im-adithya** [comment]
I think you mixed up some old commits again (see the translation strings)

**Comment by manavdesai27** [comment]
> I think you mixed up some old commits again (see the translation strings)

Could you help me resolve this?

**Comment by escapedcat** [comment]
Maybe "merge" is just easier.

**Pull request closed without merging**
