### PR TITLE
add: bug/feature template forms

### LINKED ISSUE #1547: Github bug/feature templates: Switch to forms
### Is your feature request related to a problem?

Our issues templates sometimes lead to missing or wrongly input information.  
Would be nice to fidn a way to "guide" a user through these when filing an issue.

### Describe the solution you'd like

Currently we use simple templates for these.  
Other projects use external services.  

Zeus uses github but with a "form-generator":
 - See: https://github.com/ZeusLN/zeus/issues/new?assignees=&labels=Bug&template=bug_report.yml
 - https://raw.githubusercontent.com/ZeusLN/zeus/master/.github/ISSUE_TEMPLATE/bug_report.yml

### PR DESCRIPTION
**Pull request by buneeIsSlo**
### Describe the changes you have made in this PR

Added github bug/feature template forms.

### Link this PR to an issue [optional]

Fixes #1547 

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### How has this been tested?

I haven't tested this. I would love to know how to.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code

### CODE REVIEW

**Comment by escapedcat** [comment]
Before merging this to test it, some feedback.

Looking at the changes it looks like our current "headlines"/"items" from our templates are not reflected in this. Would be nice to reflect the current structure. See:
- https://github.com/getAlby/lightning-browser-extension/issues/new?assignees=&labels=%F0%9F%90%9E+bug&template=bug_report.md&title=
- https://github.com/getAlby/lightning-browser-extension/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=

You know what I mean?  
Some points in the changes can be nice add-ons though, i.e. the "Did you check if a similar issue already exists" can be helpful.  

> I haven't tested this. I would love to know how to.

Creating a new test-repo in Github with these templates might work.

**Comment by buneeIsSlo** [comment]
Cool. I'll make the necessary changes and post screenshots in a bit.

**Comment by buneeIsSlo** [comment]
@escapedcat Below are the screenshots, let me know if you want me to change anything else.

## Bug report
bugReport

## Feature report
featureReport

**Comment by escapedcat** [comment]
Thanks for this @buneeIsSlo !  
I think we can leave out the `[optional]`-text now that we use the `*` to indicate required fields.  
Apart form that this looks great.  
@im-adithya @reneaaron @lisabaut what do you think?

**Comment by buneeIsSlo** [comment]
Ok, will fix that soon. You can [test the forms here](https://github.com/buneeIsSlo/TEST-ISSUE-TEMPLATES/issues/new/choose).

**Comment by lisabaut** [comment]
Thanks for the testing link.

Looks good to me 👍 

One tiny thing I would change:

"Screenshots of the changes[optional]" => "Screenshots [optional]"

Because the word "changes" is misleading in my opinion
and the description below describes well what the screenswhots should show.

**Comment by buneeIsSlo** [comment]
Made the final changes :)

**Review by escapedcat — APPROVED** [review]

**Comment by buneeIsSlo** [comment]
@escapedcat Hey, Is it cool if I go ahead and delete the test repo?

**Comment by escapedcat** [comment]
> @escapedcat Hey, Is it cool if I go ahead and delete the test repo?

Yes, thanks for you support!

**Comment by buneeIsSlo** [comment]
Thanks for the opportunity :)

**Pull request merged**
