### PR TITLE
Chore/deps swc 220 plus workaround

### PR DESCRIPTION
**Pull request by escapedcat**
Latest swc updates break our Jest setup. There's is a workaround but we still need to adjust our setup.  
Staying on `v205` is currently working for us.

## SWR and Jest

See this discussion for SWR with Jest
=> https://github.com/swc-project/swc/discussions/5151#discussioncomment-3149154

### CODE REVIEW

**Comment by bumi** [comment]
what is this one about?

**Comment by escapedcat** [comment]
> what is this one about?

Adjusted the description

**Comment by bumi** [comment]
is this still active or can we close it?

**Comment by escapedcat** [comment]
> is this still active or can we close it?

We should do this

**Comment by bumi** [comment]
so then let's solve this. July is already very old.

**Comment by escapedcat** [comment]
It's about priorities. Happy to touch this after the manifest.

**Review by lisabaut — APPROVED** [review]
Thanks, I added the link to the swr discussion to the description for later documentation.

I think, your current fix with removing `spyOn` is ok for now.

**Comment by escapedcat** [comment]
> Thanks, I added the link to the swr discussion to the description for later documentation.
> 
> I think, your current fix with removing `spyOn` is ok for now.

Thanks, already watching that discussion.

**Pull request merged**
