### PR TITLE
fix: account new button vertical alignment

### LINKED ISSUE #1991: [BUG] Buttons not aligned in Portuguese language
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Add new account, the buttons are not aligned in Portuguese language. In English is ok.

### Screenshots [optional]

photo_2023-01-17_13-52-34

### Steps To Reproduce

1- Change the language to Portuguese Brazilian
2- Go to Add new account

### Expected behavior

The buttons from the two columns aligned.

### Alby information

Alby: 1.24

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

None

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

Add min-height to ConnectorPath component description to align buttons if description on one side is single line on the other is double line. See screenshots.

### Link this PR to an issue [optional]

Fixes #1991

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]

Bildschirmfoto 2023-01-19 um 07 48 01
Bildschirmfoto 2023-01-19 um 07 47 41

### How has this been tested?

Manually

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]
utACK

**Comment by lujakob** [comment]
Failed on "[chromium] › 001-createWallets.spec.ts:96:7 › Create or connect wallets › successfully creates an Alby wallet " - is there a testnet dependency that might be down? Who knows how to address this failing test?

**Comment by escapedcat** [comment]
> Failed on "[chromium] › 001-createWallets.spec.ts:96:7 › Create or connect wallets › successfully creates an Alby wallet " - is there a testnet dependency that might be down? Who knows how to address this failing test?

All good, this is not related to your code. Will be solved here:
https://github.com/getAlby/getalby.com/pull/343

**Comment by lujakob** [comment]
@escapedcat who is going to merge this PR? How do you handle merging PRs? The creator of the PR after approval or any other way?

**Pull request merged**
