### PR TITLE
Change grid to allow 5 connectors per row

### PR DESCRIPTION
**Pull request by secondl1ght**
@bumi wanted to have all on one row instead of having 1 connector by itself. 

image

### CODE REVIEW

**Comment by bumi** [comment]
whoot. you're fast. 
@johnsBeharry are you OK with that. and then we think what do do once we have Galoy in?

**Comment by johnsBeharry** [comment]
We won't have Galoy, as that's just the tech from what I understand. So it will be BitcoinBeach, and I think [Bitcoin Jungle](https://bitcoinjungle.app). @vindard is that correct? OR do those two apps share a database?

Either way I reckon that list will continue to grow, and I'd opt we go for a more App Store style card. Similar to what Auwal did

Screenshot 2022-01-25 at 1 07 12 AM

**Comment by bumi** [comment]
Check out the #434 branch. It is a Galoy connector.

I like the app store style cards...those can hold enough information.

**Comment by bumi** [comment]
but are you OK with this PR for this release?

**Review by johnsBeharry — APPROVED** [review]
LGTM

**Comment by vindard** [comment]
> So it will be BitcoinBeach, and I think [Bitcoin Jungle](https://bitcoinjungle.app)

I guess tbd because the only thing that separates these two is the api link we point at.

**Comment by secondl1ght** [comment]
Should we create a new issue to track the connector re-design?

**Comment by bumi** [comment]
:+1: please do.

**Pull request merged**
