### PR TITLE
fix: register listeners sync

### LINKED ISSUE #2305: [BUG] An unexpected error occurred (Could not establish connection. Receiving end does not exist)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking on the extension icon while logged in sometimes throws and error and shows a logged-out state

### Screenshots [optional]

image

image

image

image

### Steps To Reproduce

First Issue:
1. Checkout and build the latest master branch (yarn run dev:chrome)
2. Login to the extension
3. Close the popup
4. Switch to a different application
5. Go back to your browser and click the Alby extension icon

Second issue:
1. Log into the extension with multiple accounts
2. Switch from LND to an Alby hosted account (2nd screenshot)

### Expected behavior

The popup opens and you are still logged in, with no errors. You can also switch accounts without errors.

### Alby information

- Master branch (latest)

### Device information

Chrome Windows

### Additional context

May be related to the recent manifest version 3 update

### Are you working on this?

None

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

Possibly fixes #2305 :crossed_fingers: 

[MV3 Migration Guide](https://developer.chrome.com/docs/extensions/migrating/to-service-workers/#register-listeners)

### CODE REVIEW

**Comment by rolznz** [comment]
@reneaaron nice! I think this fixes this particular issue. I am just worried about what will happen if we receive requests while the init() function is still running, which might introduce strange errors. I still think it would be good to wait for the service worker / background script to finish the init() before we start interacting with it.

CC @bumi

**Comment by reneaaron** [comment]
> I am just worried about what will happen if we receive requests while the init() function is still running, which might introduce strange errors. I still think it would be good to wait for the service worker / background script to finish the init() before we start interacting with it.

What would we do with messages that are sent before init() finished then? Drop them? Couldn't that lead to other problems? (promises not being resolved, etc?)

**Comment by rolznz** [comment]
> > I am just worried about what will happen if we receive requests while the init() function is still running, which might introduce strange errors. I still think it would be good to wait for the service worker / background script to finish the init() before we start interacting with it.
> 
> What would we do with messages that are sent before init() finished then? Drop them? Couldn't that lead to other problems? (promises not being resolved, etc?)

@reneaaron this fixes the issue for me and was just raising the possibility of other issues, but I can't produce them. I think we should merge this 🚀

**Comment by bumi** [comment]
I don't think it is possible to easily handle messages sent before the init is done.

**Pull request merged**
