### PR TITLE
feat: update alerts to use new toast component

### LINKED ISSUE #934: replace `alert()` with toastify alerts
We recently introduced react-toastify for nicer alerts: https://github.com/getAlby/lightning-browser-extension/pull/852

we should use this in all frontends instead of the browser native `alert`

### PR DESCRIPTION
**Pull request by secondl1ght**
#### Link this PR to an issue
Fixes #934 

#### Type of change (Remove other not matching type)

- New feature (non-breaking change which adds functionality)

#### Describe the changes you have made in this PR -
I have updated all instances of `alert()` and changed it to the corresponding `toast()`.

#### How Has This Been Tested?
I did not test every single toast call but I did test to make sure toast works.

#### Checklist:

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]

**Review by bumi — CHANGES_REQUESTED** [review]
Does the toast messages work in the storybook stories? 
I think there is no toastcontainer, so maybe we need to leave it there to `alert`. the alerts there are only example implementations anyway

**Comment by secondl1ght** [comment]
Sounds good, maybe we could add a toastcontainer to the stories but because it is just examples like you said then let's just revert back to `alert`. I am not sure how many people use the Storybook stories anyway.

**Review by bumi — COMMENTED** [review]
I think it is a good practice to have the npm imports above the local imports. 
This is how it currently is in the code. 

Can you move the `import { toast } from "react-toastify";` above the local imports?

**Review by bumi — APPROVED** [review]

**Comment by escapedcat** [comment]
@secondl1ght @bumi @dylancom what do you think about using a plugin to align all our import sortings? i.e. https://github.com/trivago/prettier-plugin-sort-imports

**Comment by bumi** [comment]
I don't have a strong opinion there. 
less dependencies is better, but if it's helpful :)

**Comment by secondl1ght** [comment]
@escapedcat I like prettier, so I'd be up for it.

**Pull request merged**
