### PR TITLE
fix: lnurl auth return value cause  error msg

### LINKED ISSUE #1874: [BUG] The format of the LNURL return value is incorrect, and the wallet's processing of the return value needs to be improved
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I set up an environment that supports authentication with LNURL locally

`res.json({ key,
                status:"ok",
                 reason:"" 
            })`
The return value of the api is spliced manually. When the field is incomplete, such as the status field is missing, the wallet prompts that the wallet has made an error. In fact, the api has made an error. You should check the api

https://medium.com/@tobiadeyemi/lightning-powered-authentication-with-lnurl-and-nextjs-d2a023309b81
https://github.com/qqqzhch/ln-auth-nextjs

### Screenshots [optional]

WX20221215-131744@2x

### Steps To Reproduce

1 Click Lightning Login on the webpage
2 Click Confirm on the webln link page
3 Click Confirm on the webln auth page, and the page prompts "Error: Cannot read properties of undefined (reading 'toUpperCase')"

### Expected behavior

Auth: Something went wrong

### Alby information

Error: Cannot read properties of undefined (reading 'toUpperCase')

### Device information

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by qqqzhch**
### Describe the changes you have made in this PR

When the result returned by the lnurl auth api is missing a field, the prompt should be Auth: Something went wrong

### Link this PR to an issue [optional]

- Fixes #1874

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]
For example, the status field is missing
WX20221215-131744@2x

after fix 
WX20221215-134759

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by bumi** [comment]
👍 great!

@escapedcat is there an easy way to add as test for this?

**Comment by escapedcat** [comment]
> is there an easy way to add as test for this?

Added tests for success and expected fail. @qqqzhch have a look if this makes sense, thanks

**Comment by qqqzhch** [comment]
> > is there an easy way to add as test for this?
> 
> Added tests for success and expected fail. @qqqzhch have a look if this makes sense, thanks

Ok, let me understand the code related to the test

**Comment by qqqzhch** [comment]
> > is there an easy way to add as test for this?
> 
> Added tests for success and expected fail. @qqqzhch have a look if this makes sense, thanks

I read the test code several times
test code  makes sense
@escapedcat

**Pull request merged**
