### PR TITLE
Add Lightning Node Connect

### PR DESCRIPTION
**Pull request by bumi**
This adds the support to connect to LND nodes through "Lightning Node Connect". It uses the official `lnc-web` npm package. LNC makes it easy and fast to connect to any LND node and removes the need to use Tor for nodes behind a NAT or firewall.

More details about LNC: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/lightning-node-connect 

For this Lightning Terminal is required on the node: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit

## Beta Testers:

Easiest is to use a Chrome/Chromium based browser and download the `chrome.zip.zip` from the comments (from github-actions), unpack the .zip, go to your browser -> Extensions, make sure you have the "Developer mode" enabled, then drag & drop the extraced zip file in. 

To get a LND pairing phrase go to your Lightning Terminal (litd) ([help](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal)) -> Lightning Node Connect -> create a new session. 
If you use Umbrel or Start9 you can easily install "Lightning Terminal" from their app stores.

Then you can choose LNC in Alby to add a new account connection.

image

#### Test questions:

* Can you connect to your LND node with LNC? 
* Does it work reliably across restarts of your browser?
* Does the WebLN demo app show channel and balance information? https://liquimercado-lnd.getalby.repl.co/dashboard
* Do payments reliably work?

## ToDo:

- [x] permission system to allow users to select the actions they want to enable for apps

### CODE REVIEW

**Comment by bumi** [comment]
CleanShot 2022-10-21 at 08 21 56@2x

**Comment by lyndonwest** [comment]
**Beta Tester**

Test questions:
Can you connect to your LND node with LNC? **Yes**
Does it work reliably across restarts of your browser? **Yes**
Does the WebLN demo app show channel and balance information? **Yes**
Do payments reliably work? **Yes, tried multiple send and receive, including LNUrl**

**Comment by bumi** [comment]
@lyndonwest thanks a lot! That's great to hear!

**Comment by liviudm** [comment]
Couldn't install extension in Firefox even after setting `xpinstall.signatures.required` to `false`.

Tested on Chrome

Can you connect to your LND node with LNC? **Yes**
Does it work reliably across restarts of your browser? **Yes**
Does the WebLN demo app show channel and balance information? https://liquimercado-lnd.getalby.repl.co/dashboard **Yes**
Do payments reliably work? **Sent to a geyser.fund project, it took several seconds, but everything went through**

**Review by GeorgeTsagk — APPROVED** [review]

**Pull request merged**
