### PR TITLE
Fix some linting warnings

### PR DESCRIPTION
**Pull request by bumi**
This fixes some linting warnings of unused variables.

Though I actually like those because it shows the developer what can be used in the function - even if it unused right now.

### CODE REVIEW

**Comment by dylancom** [comment]
@bumi if you don't agree with certain rules, we can add our own rules to estlintrc. (Rules that override the rules we extend)

**Comment by bumi** [comment]
I think we should go with the most widely used and accepted standard. 
what are your thoughts on those?

**Comment by dylancom** [comment]
In general I prefer to go for the most standard rules. But if there's a good reason for an exception I'd say we can add that.
We could add for e.g.: `"@typescript-eslint/no-unused-vars":["error", { "args": "none" }]` to our rules so unused vars still lead to warnings except for function arguments.

**Comment by bumi** [comment]
and what is your opinion?

**Comment by dylancom** [comment]
For our use-case we can add the exception.

**Comment by bumi** [comment]
so what do you think, what should we enforce?

**Comment by dylancom** [comment]
This can be closed in favor of https://github.com/getAlby/lightning-browser-extension/pull/481

**Pull request closed without merging**
