### PR TITLE
feat: responsive testconnection

### PR DESCRIPTION
**Pull request by pavanjoshi914**
### Describe the changes you have made in this PR
make test connection screen responsive and refactor headings

### Link this PR to an issue [optional]

(Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]
image

### Checklist

- [X] Self-review of changed code
- [X] Manual testing
- [X] Added automated tests where applicable
- [X] Update Docs & Guides
- For UI-related changes
- [X] Darkmode
- [X] Responsive layout

### CODE REVIEW

**Review by reneaaron — CHANGES_REQUESTED** [review]
I think the names of those fields are not necessary at this point. A user doesn't know what an "alias" is, anyway.

**Comment by pavanjoshi914** [comment]
will this work?
image

**Comment by pavanjoshi914** [comment]
the only motive here is to split alias and account name as it's too long for smaller screens as it was inline before

**Comment by reneaaron** [comment]
I don't understand. The account name & alias have always been separated by a dash, right? 

image

**Comment by pavanjoshi914** [comment]
yup but on smaller screens it looks something like this. and the account name are mostly continuous strings. so instead of breaking words or hiding overflows i wished to separate both on new line
image

**Pull request merged**
