### PR TITLE
feat: add account menu identicon avatar

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

As described in the issue the changes add an Identicon avatar icon to the accounts menu. See screenshots for more infos.

### Link this PR to an issue [optional]

Fixes [_#1987_](https://github.com/getAlby/lightning-browser-extension/issues/1987)

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]

Bildschirmfoto 2023-01-16 um 20 10 18
Bildschirmfoto 2023-01-16 um 20 10 26
Bildschirmfoto 2023-01-16 um 20 10 40

### How has this been tested?

Tested manually by running extension.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by lujakob** [comment]
@reneaaron a few notes on this:
* Is this what you imagined?
* I had an IDE error and commit error complaining about missing types for the new lib import. As I could not find `@types/react-identicon` I added declare module in https://github.com/getAlby/lightning-browser-extension/pull/1990/files#diff-5f2ca1b1541dc3023f81543689da349e59b97c708462dd8da4640b399362edc7R19
Is this the right place?
* I'm not sure what you intended: the issue description sounds like there might be different options for avatars, which would make a distinct react component for the avatar viable. Should I already pack `<Identicon>` into a component or leave as is for now?

**Comment by escapedcat** [comment]
> I had an IDE error and commit error complaining about missing types for the new lib import. [...]
> Is this the right place?

👍  just wondering if there's a more maintained package which comes with types

**Comment by lujakob** [comment]
> > I had an IDE error and commit error complaining about missing types for the new lib import. [...]
> > Is this the right place?
> 
> 👍 just wondering if there's a more maintained package which comes with types
> 
> Have a look at the failing unit-test

This here seems to be similar and has types... I'll test it later..

https://github.com/polkadot-js/ui/blob/master/packages/react-identicon/src/types.ts

**Comment by escapedcat** [comment]
> This here seems to be similar and has types... I'll test it later..
> https://github.com/polkadot-js/ui/blob/master/packages/react-identicon/src/types.ts

Exciting times, lightining projects using polkadot packsges 😁

**Comment by lujakob** [comment]
> > This here seems to be similar and has types... I'll test it later..
> > https://github.com/polkadot-js/ui/blob/master/packages/react-identicon/src/types.ts
> 
> Exciting times, lightining projects using polkadot packsges 😁

Yes I wasn't sure if the PR gets declined and I get a shitstorm for this "infiltration" ;-)

**Comment by reneaaron** [comment]
> Is this what you imagined?

Nice work, thanks for the PR! 👌

> I'm not sure what you intended: the issue description sounds like there might be different options for avatars, which would make a distinct react component for the avatar viable. Should I already pack <Identicon> into a component or leave as is for now?

I guess that's fine for now. We will introduce this component as we see the need for it (and we know what props we need for that). 

> Yes I wasn't sure if the PR gets declined and I get a shitstorm for this "infiltration" ;-)

The list of dependencies here is quite big IMO (given the job to get done here) so I'm not quite sure we really want to include this particular library.  
https://github.com/polkadot-js/ui/blob/master/packages/react-identicon/package.json#L22

Maybe this one is an alternative? 
https://github.com/nusu/avvvatars

**Comment by lujakob** [comment]
> > Is this what you imagined?
> 
> Nice work, thanks for the PR! 👌
> 
> > I'm not sure what you intended: the issue description sounds like there might be different options for avatars, which would make a distinct react component for the avatar viable. Should I already pack  into a component or leave as is for now?
> 
> I guess that's fine for now. We will introduce this component as we see the need for it (and we know what props we need for that).
> 
> > Yes I wasn't sure if the PR gets declined and I get a shitstorm for this "infiltration" ;-)
> 
> The list of dependencies here is quite big IMO (given the job to get done here) so I'm not quite sure we really want to include this particular library. https://github.com/polkadot-js/ui/blob/master/packages/react-identicon/package.json#L22
> 
> Maybe this one is an alternative? https://github.com/nusu/avvvatars

I also would say let's forget the polkadot package. The avvvatars package seems modern, but I personally don't like the round avatars from a visual standpoint. But if you don't mind and opt for it, I can implement them.

https://avvvatars.com/

Also I would't see a problem with adding the module declaration in the custom.d.ts.

Just let me know what you prefer.

**Comment by lujakob** [comment]
I have another option with the avvvatars lib in https://github.com/getAlby/lightning-browser-extension/pull/1992

**Comment by lujakob** [comment]
I will close this one in favour of https://github.com/getAlby/lightning-browser-extension/pull/1992

**Pull request closed without merging**
