### PR TITLE
Feature/better tor support

### LINKED ISSUE #1162: Extra symbols in the notification of taken email
**Bug description**

Extra symbols in the notification of taken email

**Screenshots**

Image

**To Reproduce**

1. Click on the extension
2. Enter the account menu (down arrow)
3. Click “add a new account”
4. Click on the Alby Wallet button
5. Enter existing email
6. Enter new password
7. Click “Continue”
8. Notification of taken email appears

**Expected behavior**

Clear notice without any extra symbols

**Alby information:**

Alby Version: [v1.12.0]
Alby installed through Google Chrome
Device information:
OS: [macOS Monterey 12.0.1 ]  
Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**
No

### PR DESCRIPTION
**Pull request by bumi**
### Describe the changes you have made in this PR

if a user has Tor installed or is using the Tor Browser there is no
need to install the companion app. - it actually also does not work.
So users of the Tor Browser should not install the companion app
and we need to use the normal connectors (and not the native connectors)

Sadly I don't know of a good way to detect the Tor Browser automatically.
(except of doing a HTTP request, which is slow and more complicated)

### Link this PR to an issue

#670
also closes #1162 #1182

### Type of change (Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)
- `feat`: New feature (non-breaking change which adds functionality)

### How has this been tested?

Use Alby with the Tor Browser and add a node that is behind Tor

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by bumi** [comment]
@escapedcat do you have any idea how to fix that linting error? (this seems independent of this PR)

**Comment by reneaaron** [comment]
Just tested it. 💪

tACK, just one thing I thing I think could be a bit easier for the user:

### Text on connection screen

I think the step for TOR users is still a bit tricky (they need to press this link before continuing). Can we maybe change it to something like that? (the download instructions could become visible as soon as the user chooses an option)

image

```html
<div>
    <div class="mb-2 font-bold">Choose your setup</div><div class="form-check mb-3">
      <input class="form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
      <label class="form-check-label inline-block text-gray-800" for="flexRadioDefault1">Alby Companion App</label>
      <small class="block mt-1 ml-4 text-xs text-gray-600">Enables your computer to connect to the TOR network.</small>
    </div>
    <div class="form-check">
      <input class="form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked="">
      <label class="form-check-label inline-block text-gray-800" for="flexRadioDefault2">Tor Browser</label>
      <small class="block mt-1 ml-4 text-xs text-gray-600">Only use this option if you are using a Tor Browser right now.</small>
    </div>
  </div>
````

**Comment by bumi** [comment]
ohh, that's awesome. do you maybe have time to put this in a follow-up PR? or we pair on this?

**Comment by bumi** [comment]
I have no idea what to do with this linting error

**Pull request merged**
