### PR TITLE
fix: remove default image in publisher card

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Removes the default image whenever there isn't one.
[It still shows up when there's an error in loading the image, though]

### Link this PR to an issue

#1379 

### Type of change (Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes (If any)

Screenshot from 2022-09-09 13-11-27

<p>

</p>

### How has this been tested?

Manually

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by bumi** [comment]
is this decided by @dvoroneca 
because we also have the #1391 idea, don't we?

**Comment by bumi** [comment]
ok, good if it's a design decision +1

We can load the image from the LNURL-pay metadata response (similar to the recipient).

With the new tipping page for Alby users where they also can upload images this could fit.

https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md#wallet-to-service-interaction-flow

that should be something like: 

```js
  function getImage {
    if (!details?.metadata) return;

    try {
      const metadata = JSON.parse(details.metadata);
      const image = metadata.find(
        ([type]: [string]) => type === "image/png;base64" || type === "image/jpeg;base64"
       );

      if (image) return image[1];
    } catch (e) {
      console.error(e);
    }
  }

// or DRY with the identifier:

function findLnurlMetadata(key) {
  if (!details?.metadata) return;

    try {
      const metadata = JSON.parse(details.metadata);
      return metadata.find(
        ([type]: [string]) => type === key
       );
    } catch (e) { 
      console.error(e);
    }
}

function getImage {
  const image = findLnurlMetadata("image/png;base64") || findLnurlMetadata("image/jpeg;base64");
  if (image) return image[1];
}
```

**Review by escapedcat — APPROVED** [review]
utACK

**Comment by escapedcat** [comment]
Tested, please rebase and I merge

**Comment by im-adithya** [comment]
Done!

**Pull request merged**
