### PR TITLE
Add section recommending Polar

### PR DESCRIPTION
**Pull request by secondl1ght**
Added section to README recommending Polar for lightning network testing while working on Alby, for those who may not know about it.

### CODE REVIEW

**Comment by bumi** [comment]
What is needed to be done to get Alby connected with Polar? is there any special setup needed because of the certificate?

**Comment by secondl1ght** [comment]
I was able to just run Polar and then connect to Alby via the LND node option by copying the REST Host into Address and Admin Macaroon.

**Comment by secondl1ght** [comment]
Not sure if this was supposed to be approved and merged but it actually got removed in PR #382 because I messed up my master branch fork, sorry I should have just left it in there maybe. Maybe a maintainer can just add this to the README if it was meant to be merged.

**Comment by bumi** [comment]
let's create a new PR and in that PR we also build a small publisher website that can be used for testing locally. 

Alby -> connects to Alice
Website -> connects to Bob

then it is easy to test Alby locally

**Comment by secondl1ght** [comment]
Can you explain a bit more what you want here? I am not sure I understand everything.

**Comment by bumi** [comment]
something like that basically: https://github.com/bumi/402-server-js (but just in a single HTML)

if you use polar and want to fully test Alby you also need a publisher website connected to polar.

**Comment by secondl1ght** [comment]
Isn't there a test like that on https://getalby.com/demo or is that different than what you were thinking?

**Comment by bumi** [comment]
the demo would not work because that one is connected to the mainnet and with polar a local development network is used. So to do a test like that we also need an website that uses the local development network.

**Comment by secondl1ght** [comment]
Oh right ok got it, I think I know what you are looking for now. Not entirely sure how to implement it, but I can give it a try.

**Pull request merged**
