### PR TITLE
feat: send screen above the fold

### PR DESCRIPTION
**Pull request by dylancom**
#### Type of change (Remove other not matching type)

- New feature (non-breaking change which adds functionality)

#### Describe the changes you have made in this PR -
- Removed the card style from the send screen as it uses a lot of space.
- Smaller avatar.
- Visually hide scrollbar as in most extensions.

#### Screenshots of the changes (If any) -
Before:
Schermafbeelding 2022-05-04 om 11 12 50

After:
Schermafbeelding 2022-05-04 om 11 12 24

### CODE REVIEW

**Comment by bumi** [comment]
great!
need to check which other prompts had it. (e.g. my make invoice prompt #776)

**Review by bumi — APPROVED** [review]

**Comment by MoritzKa** [comment]
looks better without the scrollbar and the smaller icon. I found the colors before (light grey and dark grey) made the text a bit more legible.

**Comment by dylancom** [comment]
@MoritzKa how about this?
I wanted the the titles to match the color of our input labels. (same as amount & comment)
Schermafbeelding 2022-05-04 om 12 02 12

**Comment by MoritzKa** [comment]
Yes. Looks good!

**Pull request merged**
