### PR TITLE
fix: dual currency input styles

### PR DESCRIPTION
**Pull request by abhiShandy**
### Describe the changes you have made in this PR

Change a few Tailwind CSS classes to fix placeholder, text and border colors in the dual currency input box

### Link this PR to an issue [optional]

This addresses a part of task 5 mentioned in #2511 

### Type of change

(Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

#### BEFORE  <> AFTER

Screenshot 2023-10-04 at 7 33 05 AM
Screenshot 2023-09-30 at 10 43 46 AM

Screenshot 2023-10-04 at 7 33 22 AM
Screenshot 2023-09-30 at 10 43 38 AM

Screenshot 2023-10-04 at 7 33 49 AM
Screenshot 2023-09-30 at 10 40 28 AM

Screenshot 2023-10-04 at 7 33 57 AM
Screenshot 2023-09-30 at 10 40 39 AM

### How has this been tested?

This has been tested visually after running `yarn run dev:chrome`

### Checklist

- [ ] Self-review of changed code
- [ ] Manual testing
- [ ] Added automated tests where applicable
- [ ] Update Docs & Guides
- For UI-related changes
- [x] Dark mode
- [ ] Responsive layout

### CODE REVIEW

**Comment by abhiShandy** [comment]
@stackingsaunter this PR makes easy changes to fix the border, text and placeholder colors in both currency input and description input below it.

**Comment by reneaaron** [comment]
@abhiShandy Thanks for the PR, however the colors don't seem to match the designs? 

https://user-images.githubusercontent.com/68239231/248509813-13fbcea9-62c3-4cbf-ae9b-aafcdc0f704b.png

Where did you get those colors from? :thinking:

**Comment by abhiShandy** [comment]
> @abhiShandy Thanks for the PR, however the colors don't seem to match the designs?
> 
> https://user-images.githubusercontent.com/68239231/248509813-13fbcea9-62c3-4cbf-ae9b-aafcdc0f704b.png
> 
> Where did you get those colors from? 🤔

I used this https://github.com/getAlby/lightning-browser-extension/issues/2511#issuecomment-1741777180

**Comment by pavanjoshi914** [comment]
it's always better to add before vs. after screenshots for such small UI changes. there are other tasks as well linked in the issue right? please specify which task among those is completed here

**Comment by pavanjoshi914** [comment]
why ```neutral``` for dark mode? same can be achieved even by tweaking gray one isnt it?

**Comment by abhiShandy** [comment]
> it's always better to add before vs. after screenshots for such small UI changes. there are other tasks as well linked in the issue right? please specify which task among those is completed here

I have added the screenshots for comparison

> why `neutral` for dark mode? same can be achieved even by tweaking gray one isnt it?

Neutral and gray are different colors

Screenshot 2023-10-04 at 7 38 48 AM
Screenshot 2023-10-04 at 7 38 53 AM

**Review by pavanjoshi914 — APPROVED** [review]

**Comment by abhiShandy** [comment]
Can we merge this?

**Review by stackingsaunter — APPROVED** [review]

**Comment by stackingsaunter** [comment]
@pavanjoshi914 good to go I think?

**Comment by pavanjoshi914** [comment]
@stackingsaunter are design's correct? @reneaaron had some design related suggestions here i think.

**Comment by abhiShandy** [comment]
closing due to lack of activity

**Pull request closed without merging**
