### PR TITLE
feat: add tipping for stackoverflow profiles

### LINKED ISSUE #1063: Tipping feature for Stackoverflow
### Is your feature request related to a problem? Please describe

Support tipping on [Stackoverflow](stackoverflow.com) profiles, i.e.:\
https://stackoverflow.com/users/16343464/mozway

### Describe the solution you'd like

Lightning address in profile should be recognized by Alby.

### Describe alternatives you've considered

none

### Additional context

Research. Further enhancement could be:  
- On a normal question page check if the 
   - Person asked the question has a LN address in the profile
   - Person whos answered was marked as "solved" has a LN address in the profile
- Offer sending sats to both or either?

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Added tipping functionality for StackOverflow

### Link this PR to an issue

Closes #1063

### Type of change (Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### How has this been tested?

https://user-images.githubusercontent.com/64399555/175388430-56071da2-567d-485a-b8ef-259897c298bd.mp4

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]

**Comment by reneaaron** [comment]
The question then is: to which user? Are you paying the user who asked the question? Or the one with the solution?

**Comment by escapedcat** [comment]
True, I think bumi had the solution-user in mind. WOuld be nice to chose or just send to both?

**Comment by reneaaron** [comment]
> True, I think bumi had the solution-user in mind. 

As currently there is no way to let the user choose from multiple recipients I'd agree with sending to the user who posted the solution. 👍

**Comment by bumi** [comment]
I'd say we go with the accepted one. Isn't this a bit of an "official" approval? 
for the others people could visit the user's profile page.

**Pull request merged**
