### PR TITLE
feat: swap inter font for open runde

### LINKED ISSUE #2612: Swap Inter font for OpenRunde
OpenRunde is a a variation of Inter but with rounded corners. It feels Alby brand with it's a bit more pleasant appeal while preserving great characteristics of Inter. Font is on the same license as Inter. There are currently 4 weights of Open Runde and those are exactly what we use. Creator of Open Runde also added [slashed zeros](https://github.com/lauridskern/open-runde/issues/2) for us to display numbers as we do now.

[OpenRunde repo](https://github.com/lauridskern/open-runde?ref=designerdailyreport.com)

image

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

Fixes #2612

### CODE REVIEW

**Comment by bumi** [comment]
The path to the font is correct in the builds?

**Comment by reneaaron** [comment]
>  The path to the font is correct in the builds?

Which builds do you mean? The font is correctly displayed in the extension: 

image

**Comment by bumi** [comment]
👍 can you make a PR for the website, too?

**Comment by reneaaron** [comment]
Will do :ok_hand:

**Pull request merged**
