### PR TITLE
Add lnurl-auth input checkbox to allowance menu

### PR DESCRIPTION
**Pull request by secondl1ght**
Linked to #148, I have started this PR but it still needs work. Me and @bumi are working on this together. I have added the input checkbox element to the allowances menus. I have just done this initial work so far and haven't looked at hooking it up yet. It will be something like ```<input type="checkbox" id="lnurl-auth" name="lnurl-auth" checked={lnurlAuth ? checked : ""}/>```. And we will have to add an onclick to change the ```lnurlAuth``` which I think is a ```boolean```. Thanks for helping with this bumi!

Screenshot:

image

image

### CODE REVIEW

**Comment by dylancom** [comment]
@secondl1ght We have a <Checkbox /> component in the Form folder that you can use.

**Comment by secondl1ght** [comment]
Awesome thanks, I've updated this to use the nice checkbox component with Alby styles.

**Comment by bumi** [comment]
wanna try to add the logic to save that value? 
you can actually just hook into how the saving of the budget is currently done.

**Comment by secondl1ght** [comment]
Ok I gave it a try, I am still getting a type error but I just pushed it anyway so that you could see it and I can fix that later if I am on the right track. Just let me know if what I did here is correct or not, I tried to follow what was already set up for the budget. But it is likely that there is still some work to be done here (maybe I am close?). Thanks!

**Comment by bumi** [comment]
I think @secondl1ght you could pick this up again and try if you now get it working

**Comment by escapedcat** [comment]
Closing in favour of #1539

**Pull request closed without merging**
