### PR TITLE
Initial draft of dark mode for feedback

### PR DESCRIPTION
**Pull request by secondl1ght**
I started working on implementing dark mode, it is chosen based on the users system settings as suggested in #305. I have only done the welcome onboarding views so far to get some initial feedback before proceeding to work on more pages. Please let me know what you think. Here are some screenshots:

image

image

image

image

image

### CODE REVIEW

**Comment by MoritzKa** [comment]
Looks actually quite good. How does it turn out if we have a more sophisticated design in the extension as suggested [here](https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Extension-(MVP)?node-id=612%3A7998) Maybe we should wait for that first?

**Comment by secondl1ght** [comment]
I'll just wait for more feedback before proceeding with converting the rest of the extension to dark mode.

**Comment by bumi** [comment]
maybe you can show it to @johnsBeharry or @GBKS to hear what they think?

**Comment by GBKS** [comment]
Looks really good, a small thing might the body text color being too low contrast. If you want to, the Bitcoin UI Kit has color palettes for dark and light modes laid out here: https://www.bitcoinuikit.com/foundation .

**Comment by secondl1ght** [comment]
@GBKS perfect thanks i'll check that out, and it seems like people generally like this so I think i'll go ahead and code up the rest of the extension and then post here when it is ready to be reviewed and merged.

**Comment by secondl1ght** [comment]
Ok I have converted the rest of the extension to dark mode! 

I will attach some screenshots here but the best way to see all of the screens would be to just load the unpacked version of my fork and play around a bit. It is very possible that I may have missed some screens because I didn't test all possible areas like adding LNbits, LNDHub, LND etc. If someone who has easy access to all of these could test all the user flows and make sure I did not miss anything that would be great. 

After review and feedback I think this is ready to be merged as long as everyone likes it.

I also did not test actually sending or receiving, is there like a testnet node I could connect to so I can check these screens?

image

image

image

image

**Comment by secondl1ght** [comment]
Note: I should probably create a dark mode for https://getalby.com/demo as well because it is very bright when you leave the dark mode Alby and go there. Just not sure where the repo for that is.

**Comment by MoritzKa** [comment]
That's great work! I think the color of the demo website is fine. We can think about enhancing the demo a bit. Today a visitor can press a pay button. What could we give a user back?

Regarding the dark mode of the extension. If there are builds available I am happy to test and review it.

**Comment by secondl1ght** [comment]
@MoritzKa here is a build you can use to try it out 
[chrome.zip](https://github.com/getAlby/lightning-browser-extension/files/7538920/chrome.zip)

**Comment by bumi** [comment]
@secondl1ght can you check the merge conflict here?

**Comment by secondl1ght** [comment]
@bumi yes please use the edits from my PR so it should look like this:

```
<!DOCTYPE html>
<html lang="en" class="antialiased dark:bg-gray-900">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Alby</title>
</head>

<body class="w-96 dark:bg-gray-900">
  <div id="prompt-root"></div>
</body>

</html>
```

**Comment by bumi** [comment]
you can also download the builds from the build artifacts: 
https://github.com/getAlby/lightning-browser-extension/actions/runs/1463580337

**Comment by secondl1ght** [comment]
I am creating a post here to track the feedback I have received so far, please let me know if I have missed anything. I will work on making these changes soon:

@dylancom 
- input fields should be lighter grey instead of white
- top navbar and other borders should stand out less and blend in more like shadows

@MoritzKa 
- some icons on the dropdown menu are black and some are grey, switch all to grey so it looks better
- same comment as dylan for white areas, needs to be grey for less contrast
- not dark mode specific but also suggested a border and rounded edges for the send screen amount box

**Comment by secondl1ght** [comment]
Ok I think I have made most of the changes based on the feedback, the one exception is moritz comments about some of the black icons. Some of these are images so do not get their styling from the Tailwinds classes, so these will be a bit trickier to style based on the dark theme. I'm open to any ideas though.

**Comment by secondl1ght** [comment]
I see there are some new conflicts here, what is the best way to resolve them? Should I make the changes to my PR or just let you know in a comment here?

Maybe we should merge this after the conflicts are resolved and then I can open a new PR for new dark mode updates? The new issue opened today should probably be its own PR anyway #403. I think that was the last item we were waiting on this for PR. What do you guys think?

**Comment by secondl1ght** [comment]
I have resolved all the conflicts and also made all the dropdown icons the same color now that they are SVGs.

**Comment by secondl1ght** [comment]
Once this gets merged if anyone has any comments after they play around with all of the screens I can still make changes going forward.

**Comment by secondl1ght** [comment]
Ok I have resolved the conflicts again on this, after it gets merged I will play around with the app more and make any dark mode adjustments that need to be made with smaller PR's for this.

**Comment by secondl1ght** [comment]
Lots more conflicts LOL.. XD. Ok I'll go through these and resolve them and do a final review and then we should be able to merge.

**Comment by secondl1ght** [comment]
Ok I resolved the conflicts but it looks like the new onboarding broke lots of the dark mode I had setup. So I'll have to go back and make changes to make it look right again.

**Comment by secondl1ght** [comment]
Ok @bumi @MoritzKa @dylancom I have made the updates so dark mode is working again with the new onboarding screen. I think this is ready for the final review. I did a pretty in-depth review to make sure all the screens look good but one more look would be good. Thanks!

Some updates screenshots:

image

image

image

image

image

image

image

image

**Pull request merged**
