### PR TITLE
chore: remove removeAccount and replace with delete

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

This [commit](https://github.com/getAlby/lightning-browser-extension/pull/157/commits/97194ff5e34b6abdf1de1520cb9bd1377f1bd2b7) first introduced this hacky fix to remove and retry. Then `deleteAccount` got added later which also handled the case of `removeAccount` https://github.com/getAlby/lightning-browser-extension/blob/b272c0c288488892ffba90fdf3b673783b83816c/src/extension/background-script/actions/accounts/delete.ts#L11 which is also used in #682 in this [commit](https://github.com/getAlby/lightning-browser-extension/pull/682/commits/84c83e6c6f41d602ba1cf16f9f6ec099ead00e50). This PR removes the use of removeAccount from another file and deletes it as a whole.

### Link this PR to an issue

None (partly related to #955)

### Type of change (Remove other not matching type)

- `chore`: Removed redundant code (updating grunt tasks etc; no production code change)

### Screenshots of the changes (If any)

_Add screenshots to help explain your problem_

### How has this been tested?

Ran all tests

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by escapedcat** [comment]
Uhm, better let us know before you tackle things without an issue. This duplicates #984 which is a draft till further "TS switch" draft PRs are being merged. After a rebase that PR will look good again.

**Comment by im-adithya** [comment]
> Uhm, better let us know before you tackle things without an issue. I believe this duplicates #984 which is a draft till further "TS switch" draft PRs are being merged. After a rebase that PR will look good again.

Sorry for that! I actually came across this while fixing #955 as renaming `delete` to `remove` makes two remove files with the same functionality!

**Comment by escapedcat** [comment]
No worries. Just want to avoid wasting your time. Let's switch this to draft and take a look when the other one is ready.

**Comment by im-adithya** [comment]
Sure!

**Comment by im-adithya** [comment]
Resolved by #984

**Pull request closed without merging**
