### PR TITLE
feat(battery): add substack battery

### PR DESCRIPTION
**Pull request by lukeojones**
### Describe the changes you have made in this PR

Add a new battery for Alby/Substack integration 🥳
The battery handles profile pages (`/profile/`) _and_ post pages (`/p/`) by evaluating the JSON-LD embedded in each page.

NB: Some posts can be co-authored (i.e. multiple authors) in which case the first author with a Lightning address will be selected.

### Link this PR to an issue [optional]

Fixes _#1263_

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]

[Video of Alby-enabled Profile and Post pages](https://user-images.githubusercontent.com/54580872/213873730-ae3e7d44-9554-4b50-a546-e09ca0a65165.mov)

### How has this been tested?

Happy path scenario tested by configuring my personal Substack Profile and ensuring that my [Profile page](https://substack.com/profile/4356578-luke-jones) and an example [Post page](https://bitsandcoins.substack.com/p/coming-soon) are both Alby-enabled. 

Tested the following additional scenarios by overriding the JSON-LD data as appropriate:

**Profile Page Tests**
- No Person or Article => No OP
- Person without description => No OP
- Person without LN Address => No OP
- Person without name => No name displayed
- Person with no image => No Image Displayed
- Person with image as string => Display Details with Rescaled Image

**Post Page Tests**
- Person with image as contentUrl => Display Details with Rescaled Image
- Author is first element => Display Details
- Author is second element => Display Details
- Neither Author is LND enabled => NO OP

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — COMMENTED** [review]
Works!
Just wondering if we need the class syntax here. No other battery is using this.

**Comment by lukeojones** [comment]
> Works! Just wondering if we need the class syntax here. No other battery is using this.

Fair comment. It's definitely not strictly needed, I just thought it helped to make the code a little more readable/expressive.
I'm happy to back that out if you think it doesn't achieve that goal though.

**Comment by escapedcat** [comment]
> It's definitely not strictly needed, I just thought it helped to make the code a little more readable/expressive. I'm happy to back that out if you think it doesn't achieve that goal though.

These batteries are often copy and pasted to create a new one. So might be good be consistent if that works or makes sense. No need to change it now. Let's see what the others say.

**Comment by lukeojones** [comment]
@escapedcat - I don't want to be a nag but is there any way I could nudge people for a review of this? I know it's now the most important issue in the backlog but would be a nice feature to have in Alby and if there are changes to make, I can get started on them. Let me know 😎

**Comment by escapedcat** [comment]
> @escapedcat - I don't want to be a nag but is there any method to nudge people for reviews of this? I know it's now the most important issue in the backlog but would be a nice feature to have in Alby and if there are changes to make, I can get started on them. Let me know 😎

No worries, I'll nudge :)

> I don't want to start tagging everyone but if there is an existing channel or similar that is used for this or something?

You can join i.e. our slack channel or join our bi-weekly calls: https://github.com/getAlby/lightning-browser-extension/#join-the-conversation

**Comment by im-adithya** [comment]
Thanks for your contribution, @lukeojones!

But we only use Classes in limited areas and we'd have to change the other batteries too to maintain consistency
So could you please revert to using functions?

**Review by im-adithya — APPROVED** [review]
Thanks @lukeojones!

**Pull request merged**
