### PR TITLE
Updated Raspiblitz connector page

### LINKED ISSUE #1618: Update the RaspiBlitz Connector Page
### Describe the bug

RaspiBlitz was updated. We need new instructions to connect to Alby.

### Screenshots of the changes [optional]
suggestion:

POWERPNT_CkA9BH8dJa

### To Reproduce

A new video is already available.

1. Click on 'Add a new account'
2. Scroll to 'RaspiBlitz' and click on it

### Expected behavior

s. screenshot

### PR DESCRIPTION
**Pull request by mviswanathsai**
### Describe the changes you have made in this PR

Updated the Raspiblitz connector page info as per #1618 

### Link this PR to an issue [optional]

Fixes #1618

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

Checked by opening the Raspiblitz connector page locally to see the wanted changes

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by MoritzKa** [comment]
I tried to followed the demo video and came up with these steps

POWERPNT_eizNkKEXJB

**Comment by bumi** [comment]
@MoritzKa we don't have the option to format text there (have lists, etc.) only plain text. 
can you two coordinate the best text and update this PR accordingly?

**Comment by MoritzKa** [comment]
@mviswanathsai do you have some time to work on it. I proposed the screenshot above that aligns with the current RaspiBlitz menu.

**Comment by bumi** [comment]
@MoritzKa this is not possible we can only show a bunch of text there (no html)  which is also in weblate (checkout weblate)

**Comment by MoritzKa** [comment]
It does not need to be formatted as a list. Right now we have each step in a new line. The same pattern can be applied for the new copy (s. screenshot).

**Comment by mviswanathsai** [comment]
@MoritzKa I will work on it as soon as I get some time

**Comment by bumi** [comment]
you can adjust this: https://github.com/getAlby/lightning-browser-extension/blob/master/src/i18n/locales/en/translation.json#L240-L241 (in weblate)

**Comment by bumi** [comment]
@MoritzKa @rolznz maybe you can do this together?

**Comment by rolznz** [comment]
Updated instructions, @MoritzKa can you review the below screenshot?

image

Note: I didn't make a change to the .onion address (both URLs in the demo video include the port number)

**Comment by rolznz** [comment]
I couldn't update this branch. I have added a new PR here: https://github.com/getAlby/lightning-browser-extension/pull/2150

**Comment by rolznz** [comment]
> @MoritzKa we don't have the option to format text there (have lists, etc.) only plain text. can you two coordinate the best text and update this PR accordingly?

@bumi I just added the numbers manually on new lines (1. ...., 2. ....). Is this OK? https://github.com/getAlby/lightning-browser-extension/pull/2150

**Comment by MoritzKa** [comment]
Thanks a lot Roland. I installed the build and tested the new screen. Looks very good to me. 
(I did not test the connection functionality)

**Comment by bumi** [comment]
@rolznz @MoritzKa is this resolved with #2150?

**Comment by rolznz** [comment]
@bumi yes, I will close this one.

**Pull request closed without merging**
