### PR TITLE
feat!: Remove Citadel connector

### PR DESCRIPTION
**Pull request by AaronDewes**
### Describe the changes you have made in this PR

The last Citadel update made some breaking API changes, so this was not working anymore. The next Citadel release will instead utilize the new API to add an account on the dashboard and will use LND/Commando directly, which will also expose more features and prevent issues with 2FA.

### Type of change

- `feat!`: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist

- [x] Self-review of changed code
- [ ] Manual testing
- [ ] Added automated tests where applicable
- [ ] Update Docs & Guides
- For UI-related changes
- [ ] Darkmode
- [ ] Responsive layout

### CODE REVIEW

**Comment by bumi** [comment]
What should we do with current users? How will they upgrade Citadel?

**Comment by reneaaron** [comment]
@AaronDewes Also the `alby.addAccount()` APIs that you initiated recently got merged which could make connecting nodes to Alby a lot easier for users, feel free to check it out:  

https://guides.getalby.com/alby-extension-apis/

**Comment by AaronDewes** [comment]
> What should we do with current users? How will they upgrade Citadel?

They will need to disconnect and re-add their wallet. But only using this API from the Citadel dashboard won't work probably because the initial setup wouldn't work...

I'll experiment a bit.

**Comment by reneaaron** [comment]
@AaronDewes What is the current status here? Is this still relevant? Do the existing APIs even work with the current release of Citadel? What connectors will be available for Citadel in future?

**Pull request closed without merging**
