### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [getAlby - lightning-browser-extension/getAlby - lightning-browser-extension](https://hosted.weblate.org/projects/getalby-lightning-browser-extension/getalby-lightning-browser-extension/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]

**Comment by escapedcat** [comment]
@bitcoinuser did you use the [Weblate UI](https://hosted.weblate.org/projects/getalby-lightning-browser-extension/) or something else? The intendation for this file was changed. Wondering how this happened. Fixed it.

**Comment by bitcoinuser** [comment]
@escapedcat Yes, I used Weblate

**Comment by escapedcat** [comment]
Cool, thanks. Let's see if this happens again. Not a big issue, just a bit annoying :)

**Comment by escapedcat** [comment]
Thanks for your work!

**Pull request merged**
