### PR TITLE
feat: handle case when user goes to onboard but doesn't setup master key

### PR DESCRIPTION
**Pull request by pavanjoshi914**
### Describe the changes you have made in this PR

user makes a call. starts the onboarding process but doesn't setup the click. now the user makes the call again. in this case route will not be overridden because of account check. also i feel we don't need that

### Type of change

(Remove other not matching type)

- `feat!`: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist

- [X] Self-review of changed code
- [X] Manual testing
- [X] Added automated tests where applicable
- [X] Update Docs & Guides
- For UI-related changes
- [X] Darkmode
- [X] Responsive layout

### CODE REVIEW

**Comment by bumi** [comment]
what was the reason to cache this?

**Comment by pavanjoshi914** [comment]
> what was the reason to cache this?

i don't know it was added later

**Review by rolznz — APPROVED** [review]
utACK

**Review by reneaaron — APPROVED** [review]
tACK

**Pull request merged**
