### PR TITLE
feat!: On manage accounts window should list the sites I logged in using LNURL-AUTH

### LINKED ISSUE #1853: [Feature] On manage accounts window should list the sites I logged in using LNURL-AUTH
### Feature description

The way it works now, I don't know which sites I used LNURL-AUTH and with which Alby accounts.

### Describe the solution

I think on manage accounts window should show which sites I logged in using LNURL-AUTH in each account.

### Describe alternatives

_No response_

### Additional context

Related to: https://github.com/getAlby/lightning-browser-extension/issues/833

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by qqqzhch**
### Describe the changes you have made in this PR

1. The accountid field is added to the allowance
2. A component is added to display the allowance under the account
3. Test related code
4. Display the newly added components on the account list page
5.  Added optional parameter accountId to listAllowances  api

### Link this PR to an issue [optional]

- Fixes #1853

### Type of change

(Remove other not matching type)

- `feat!`: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Screenshots of the changes [optional]

WX20221221-190007

WX20221221-185828

WX20221221-185845

### How has this been tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

### Checklist

- [ ] My code follows the style guidelines of this project and performed a self-review of my own code
- [ ] New and existing tests pass locally with my changes
- [ ] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by bitcoinuser** [comment]
Instead of the "login to 2 sites", I would add favicons of sites, something like this:

Screenshot_2022-12-16-23-05-08-041_com twitter android

**Comment by qqqzhch** [comment]
> Instead of the "login to 2 sites", I would add favicons of sites, something like this:
> 
> Screenshot_2022-12-16-23-05-08-041_com twitter android

Good suggestion. This display mode is better. I'll try to change it to this display mode

**Comment by qqqzhch** [comment]
screenshot-20221217-161030

**Comment by escapedcat** [comment]
We need to find a better approach to deal with this issue first. See https://github.com/getAlby/lightning-browser-extension/issues/1853#issuecomment-1361533990

**Pull request closed without merging**
