### PR TITLE
add eclair connector

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Review by kiwiidb — CHANGES_REQUESTED** [review]
Would it be possible to also add the connector to the `options/ChooseConnector/index.jsx` screen? Right now you only added it to the "onboarding" ChooseConnector screen.

**Comment by bumi** [comment]
yeah, we sadly got some slight code duplication here. it is kinda the same but not 100%. (needs refactoring at some point)

**Comment by dylancom** [comment]
Just refactored this in: #516 (So we only have 1 < ChooseConnector /> component and define the connector routes in 1 place).

**Comment by secondl1ght** [comment]
Testing: I have tested this and was able to successfully connect an eclair node to Alby. Nice work @kiwiidb 👍

**Comment by fiatjaf** [comment]
Thank you for finishing this. I was going to get to it someday.

**Comment by bumi** [comment]
thanks again @fiatjaf for adding this. will go online in the next release

**Review by bumi — APPROVED** [review]

**Pull request merged**
