### PR TITLE
feat: add prompt for webln makeInvoice calls

### LINKED ISSUE #459: User prompt for makeInvoice call
The user should be able to confirm the first makeInvoice call similar to the confirmPayment call and the [signMessage call](https://github.com/getAlby/lightning-browser-extension/issues/242)

By default we should remember that decision and only ask the user once but provide a checkbox for this.

### PR DESCRIPTION
**Pull request by bumi**
#### Link this PR to an issue
Fixes #459

#### Type of change (Remove other not matching type)
- New feature (non-breaking change which adds functionality)

#### Describe the changes you have made in this PR -
So far we did not prompt the user to create invoices.
With this change we now always show a prompt and ask the user for confirmation.
In the future we should add some "allowance" like system for invoices, too. Or allow the user to "remember" the decision for that website

#### Screenshots of the changes (If any) -
image
image

#### How Has This Been Tested?

do a `webln.makeInvoice()` call

#### Checklist:

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by dylancom** [comment]
I think it would be better UX wise to just show text instead of an input when amount or memo is disabled.
(Visually it still makes you think that you could enter something)

**Comment by bumi** [comment]
@dylancom updated. can you check again?

**Comment by dylancom** [comment]
Route not found: webln/makeInvoice

**Comment by bumi** [comment]
merged to release :)

**Pull request merged**
