### PR TITLE
Feat/performance improved get formatted fiat

### LINKED ISSUE #2031: [Feature] Enable performance improved getFormattedFiat for transforming list of payments
### Feature description

The SettingsContext getFormattedFiat function is used to convert sats into fiat in several places of the app. The rate is fetched through messaging to the background script where an HTTP request is made. This request is cached for 10 minutes.

I found three places in the app, where this async getFormattedFiat function is called in a loop, traversing over payments. Even though the final HTTP request is cached for 10 minutes, I find it quite expensive (even though I don't have the exact number on performance costs) The three places are

https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Publisher.tsx#L54
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/DefaultView/index.tsx#L95
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/DefaultView/index.tsx#L157
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/Home/AllowanceView/index.tsx#L63

### Describe the solution

As the rate is the same for all payments in the loop, I propose the get the rate before the loop and only transform the number into an object inside the loop.

Currently, fetching the rate and transforming the data in one function:
https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/context/SettingsContext.tsx#L74-L84
makes sense for all of the places where a single number is converted. 

For the places above where a potentially long array of payments needs to be transformed, I propose to provide a slight refactor and expose a function in SettingsContext, where the number and rate is provided as arguments to make it sync. To improve the loops, the rate would be fetched before the loop and inside the loop the sync function is used, being provided the rate and number.

I stumbled upon this working on the "transactions page" feature. So I could do this immediately, as I can use it in this feature.

### Describe alternatives

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

Remove blocking `getFormattedFiat` from loops to improve performance. Get the rate with `getCurrencyRate` and just do the non-blocking `getFormattedFiatFromRate` inside the loop.

The changes are: Separate `getFormattedFiatUtil` from SettingsContext `getFormattedFiat` and export `getCurrencyRate` and `getFormattedFiatFromRate`.

The relevant changes are in SettingsContext. The application of this simplification and performance improvement is in the three screen components.

This is also needed for the new https://github.com/getAlby/lightning-browser-extension/issues/2027

### Link this PR to an issue [optional]

Fixes #2031

### Type of change

(Remove other not matching type)

- `refactor`: Performance improvement

### How has this been tested?

Manually.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by escapedcat** [comment]
lgtm

**Comment by im-adithya** [comment]
Thanks for the PR @lujakob!

But I think `getFormattedFiat` is already optimized to cache:

`getCurrencyRate` only calls the `api.getCurrencyRate` on currency change (so in the for loop case, the rates are cached in the localRef)
https://github.com/getAlby/lightning-browser-extension/blob/fb3b637e2f34e22dff3d13cb81b7f0ff6d8135e0/src/app/context/SettingsContext.tsx#L74-L86

And `api.getCurrencyRate` uses the browser storage to cache currency rates (for 10 minutes) (used when the user changes currency back and forth)
https://github.com/getAlby/lightning-browser-extension/blob/fb3b637e2f34e22dff3d13cb81b7f0ff6d8135e0/src/extension/background-script/actions/cache/getCurrencyRate.ts#L62-L73

**Comment by lujakob** [comment]
@im-adithya I saw the 10 minute caching. But I completely overlooked the userRef caching in SettingsContext. Then I guess my changes are unnecessary. I just close the PR then, ok?

**Comment by im-adithya** [comment]
Sure, thanks!

**Pull request closed without merging**
