### PR TITLE
Feat/i18n zh cn

### PR DESCRIPTION
**Pull request by escapedcat**
Chinese is at 84%: https://hosted.weblate.org/projects/getalby-lightning-browser-extension/getalby-lightning-browser-extension/  
Other languages we already support have a similar percentage.
像差不多吧

- switched 聪 to sat/sats, we shouldn't translate these

### CODE REVIEW

**Comment by escapedcat** [comment]
@qqqzhch @ra5pvt1n you wanna give this a try? 谢！

**Comment by ra5pvt1n** [comment]
Will check/update in the coming days. It's been a hectic couple of weeks. 

My opinion regarding sats - since Satoshi is a Japanses name it can be transliterated into Han characters. Not everyone can read Latin alphabets or understand basic phonology and we should not raise the barrier of entry for potential users. 

But indeed some sort of translation standard would be helpful to keep different projects consistent. Do you know of any initiatives working on standardising translations?

**Comment by bumi** [comment]
wow that's amazing! maybe we can reach out on twitter and other communities about standardising translations? and what's the current preferred way?

**Comment by bumi** [comment]
I guess I can merge it for now and we update the words once decided?

**Comment by ra5pvt1n** [comment]
Yes do merge. 

I don't have a twitter account haha, and I don't know if there's a large Chinese speaking community there (perhaps from Hong Kong). Maybe @escapedcat @qqqzhch are more informed about this topic - where is the community most active?

The current preferred way for me is using the character 聪 for sats (also in RoboSats translations).

**Comment by qqqzhch** [comment]
@escapedcat  @ra5pvt1n  
OK, there is a problem with the front-end time of my environment. I'll take a look at this after I fix it

**Pull request merged**
