### PR TITLE
fix(battery): youtube live stream

### PR DESCRIPTION
**Pull request by escapedcat**
apply twitter solution to YT battery

### CODE REVIEW

**Comment by bumi** [comment]
Why is this needed? Is this only for the live stream videos, why?

I am actually not sure if this is not too much and is it worth it?

**Comment by escapedcat** [comment]
Dunno, this came up during the conference live-stream. @reneaaron asked me to have a look, so I did. This seems to solve it. Not sure how much this is needed. Was just a first draft to test it.

**Comment by bumi** [comment]
hmm, ok, then I'd say it should be checked if it can be done differently. 
I'd assume that the DOM is just slightly different on a live stream? or why did you add the observer that fires whenever the DOM changes?

**Comment by escapedcat** [comment]
It's not different. Somehow the live-stream makes the dom "slower" 90% of cases.  
In chromoum (which does not support the live-streams out of the box Alby always was finding the address and turned blue.  
In chrome it only sometimes found it or only after clicking the extension-icon.  
Applying Dylans twitter code helped with this.

**Pull request closed without merging**
