### PR TITLE
Revert "fix: revert browser targets"

### PR DESCRIPTION
**Pull request by escapedcat**

### CODE REVIEW

**Comment by escapedcat** [comment]
🎶 One More Time 🎶 🎶   
Let's revert the revert of the revert 😁

**Comment by kiwiidb** [comment]
Can be merged, confirmed that the problem was on my side.

**Comment by escapedcat** [comment]
> Can be merged, confirmed that the problem was on my side.

More like on 🔥 🦊 side...

**Review by kiwiidb — APPROVED** [review]

**Comment by escapedcat** [comment]
> why would it now work?

Because the issue was Firefox-reload, not the code. Let's have a look together to double check?

**Comment by bumi** [comment]
hmm...

**Comment by escapedcat** [comment]
😱

**Pull request merged**
