### PR TITLE
feat: linktree battery

### PR DESCRIPTION
**Pull request by im-adithya**
### Describe the changes you have made in this PR

Adds Linktree battery

### Link this PR to an issue

#1415

### Type of change (Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### How has this been tested?

Tested Manually.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Review by escapedcat — APPROVED** [review]
utACK

**Comment by MoritzKa** [comment]
@im-adithya could you describe where exactly Alby can detect the Lightning Address on a LinkTree page?
My issue was not specific enough. 
Where did you test it?
On this page Alby could not detect the Lightning Address that is written in the bio of the page owner.

**Comment by im-adithya** [comment]
I thought people would be adding a link to https://getalby.com/p/creator page here...

**Comment by bumi** [comment]
Isn't it more likely that people add a link to getalby.com/p/you than adding a lightning address?
but @im-adithya I guess we can again do both.

**Pull request merged**
