### PR TITLE
feat: lnurlpay screen toggle more fields

### LINKED ISSUE #2370: Hide optional inputs under "More" button on transacting screens
Solves https://github.com/getAlby/lightning-browser-extension/issues/1662

Currently, users when transacting, almost always need to scroll down to see buttons to cancel or send the payment, eg:

Screenshot 2023-04-25 at 00 43 21

Let's hide those under "More" button/link, so action buttons will be seen immediately:

Screenshot 2023-04-25 at 00 44 55

### PR requirements:
- Must involve all transacting screens with optional fields hidden in this way in the popup view
- Does not need to be implemented in extended (desktop) view
- Link default state color is blue600 and blue700 on hover (both light and dark theme)

### PR DESCRIPTION
**Pull request by lujakob**
### Describe the changes you have made in this PR

Toggle more fields on lnurlpay screen to have buttons visible.

### Link this PR to an issue

Fixes #2370

### Type of change

(Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]

Bildschirmfoto 2023-04-24 um 21 07 04

Bildschirmfoto 2023-04-24 um 21 07 12

### How has this been tested?

Manually

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by lujakob** [comment]
@stackingsaunter regarding your requirements:

* Must involve all transacting screens with optional fields hidden in this way in the popup view
I checked all screens that are linked from the "Send" screen and found none, except lnurlpay screen (which is the one in your design). I have nothing in mind and am not aware of how to skip through all possibilities/screens. Is there anything I missed?

* Link default state color is blue600 and blue700 on hover (both light and dark theme)
As the recommended colors didn't show up in  the IDE classes auto suggestion I searched for font color classes in the project and found the `Hyperlink` component utilizing `text-blue-700 hover:text-blue-500`. The only place this component is used is in Unlock and ConfirmSignMessage. Anyways, I just used the Hyperlink here as well.

**Comment by stackingsaunter** [comment]
> * Must involve all transacting screens with optional fields hidden in this way in the popup view

I am not aware how it is structured in the code. I know that different optional fields appear depending on LNURL, eg:
Screenshot 2023-04-25 at 12 12 35
But it seems it works for all in this build!



> * I just used the Hyperlink here as well.

That's OK, Rene will update hyperlink colors separately 

Thanks @lujakob for this PR!

**Comment by stackingsaunter** [comment]
@lujakob hey I discussed the change with @reneaaron and we decided to pull of "Comment" input out of "More", as this is quite often used and important field. Could you move it out?

Screenshot 2023-04-25 at 14 59 42

This will make users still need to scroll, but I am working on changing other elements (ln address box) to make it all fit, but that will be a seperate issue.

Also, could you delete the 1px border/divider above the buttons as well? Thank you!

Screenshot 2023-04-25 at 15 02 40

**Comment by lujakob** [comment]
> @lujakob hey I discussed the change with @reneaaron and we decided to pull of "Comment" input out of "More", as this is quite often used and important field. Could you move it out?
> 

> This will make users still need to scroll, but I am working on changing other elements (ln address box) to make it all fit, but that will be a seperate issue.
> 
> Also, could you delete the 1px border/divider above the buttons as well? Thank you!
> 

@stackingsaunter 

* I moved the comment field to always display
* I removed the border as suggested
* I cleaned up the margin/paddings. At least it's possible to notice there is more UI coming (see screens)

Bildschirmfoto 2023-04-25 um 12 17 56
Bildschirmfoto 2023-04-25 um 12 18 13

**Review by stackingsaunter — APPROVED** [review]
tACK

**Comment by reneaaron** [comment]
Thanks @lujakob, awesome job! :+1: (Great that you extracted those inline checks into methods, a lot easier to read now!)

tACK

**Pull request merged**
