### PR TITLE
Limit tx history in popup to most recent 10

### PR DESCRIPTION
**Pull request by secondl1ght**
Related to issue #310 I limited the number of transactions displaying in the popup to the most recent 10. I also updated the header to say 'Recent Transactions' so it is more clear that it does not include all of them. I just picked the number 10 but we can change it if everyone thinks that is too short, maybe 21 would be better?

image

### CODE REVIEW

**Comment by bumi** [comment]
thanks for the PR. 

can you check if we can limit the amount of payments in the action? Then this applies to everywhere we might load the payments. 
We use [dexie](https://dexie.org/) there, it should have some offset or some standard pagination functions.

**Comment by secondl1ght** [comment]
What do you mean by 'in the action', do you mind linking to the code the are referring to?

**Comment by bumi** [comment]
I think this is where we load the payments: 

https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/allowances/getById.js#L20-L24

and:
https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/actions/payments/all.js#L6

If we limit the payments in the view we still load all payments and return them to the view.
We could add some pagination there then we do not need to take care of it in every view.

**Comment by bumi** [comment]
if you want we can also pair on this one.

**Comment by secondl1ght** [comment]
Sorry I've been super busy and haven't had a chance to dive into this yet. I had a quick look though and it looks like it involves some backend stuff, I am interested in learning that. I wouldn't turn down an opportunity to pair with you if you're offering. I could probably figure it out by myself but would take longer. I'll message you in Slack about setting up a time! Thanks :)

**Comment by secondl1ght** [comment]
Looks good @bumi thanks for pairing on this!

**Review by bumi — APPROVED** [review]

**Pull request merged**
