### PR TITLE
fix(home): prefer lndata over allowance in publishercard

### LINKED ISSUE #1483: When an allowance is set the origin data from current tab is being shown in the publisher card on the home screen
### Steps to reproduce

1. Go to a [youtube channel](https://www.youtube.com/watch?v=-WAZ2UCabZs#) with a Lightning Address configured in their channel (with existing allowance for YT)
2. Open the extension popup
    image
3. You will see metadata from the page (and not from the creator) like on the homescreen:
    image

### Expected outcome

See the data from the creator on the `PublisherCard` instead of `Youtube`

### PR DESCRIPTION
**Pull request by escapedcat**
### Describe the changes you have made in this PR

Prefer matching ln-address info over general origin info

### Link this PR to an issue

Fixes #1483

### Type of change (Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

Tested on YT with monvol

### CODE REVIEW

**Comment by bumi** [comment]
cc @reneaaron

**Review by reneaaron — APPROVED** [review]
utACK

**Comment by im-adithya** [comment]
Two concerns:
- But what if the user presses the back button? [They would then see the MONVOL publisher card again]
- Wouldn't this completely remove the allowance information from the popup, what if there's a site like BOLT.FUN (where users also require allowance information) which also has an ln address within it?

**Comment by reneaaron** [comment]
ad @im-adithya 

> But what if the user presses the back button? [They would then see the MONVOL publisher card again]
I think this is addressed with #1490 

> Wouldn't this completely remove the allowance information from the popup, what if there's a site like BOLT.FUN (where users also require allowance information) which also has an ln address within it?

It should just prefer the current pages data (picked up by a battery) over the data from the allowance. If there is no data available on the current page the information from the allowance should still be displayed. Also the allowance is only relevant for WebLN calls on the page (not for payments to creators picked up by a battery).

@escapedcat I just tested the PR and noticed some behavior (probably not related to the PR though):

Currently there is no more back button and it seems to start in the HomeScreen: (instead of the PubsliherScreen) 🤔

image
https://www.youtube.com/watch?v=-WAZ2UCabZs#

**Comment by escapedcat** [comment]
@im-adithya 
> But what if the user presses the back button? [They would then see the MONVOL publisher card again]

Yes, but that's just default behaviour, no? If there's no allowance but a ln-address is found you see the publisherCard on the home-screen anyways.

> Wouldn't this completely remove the allowance information from the popup, what if there's a site like BOLT.FUN (where users also require allowance information) which also has an ln address within it?

Not completely. It will still show the url, i.e.:
image


@reneaaron 
> Currently there is no more back button and it seems to start in the HomeScreen: (instead of the PubsliherScreen) 🤔

Which color does the Alby favicon have? See my screenshot in this comment. This looks correct to me, no? For me it takes soem time till YT loaded everythign and only then the icon is green and only then I get the allowance view inclduign the back-button.

**Review by im-adithya — APPROVED** [review]

**Pull request merged**
