### PR TITLE
Add integration tests using Cypress and Puppeter

### LINKED ISSUE #556: Setup UI tests for the extension
We should be able to use Playwright, Puppeteer etc. and also hosted services to test UI flows.
I am opening this issue to collect some links for this. 

https://www.cypress.io/
https://github.com/microsoft/playwright
https://www.lambdatest.com/online-browser-testing
https://www.browserstack.com

### Cypress
+ https://www.cypress.io/
+ https://medium.com/@knoldus/how-to-load-chrome-extension-in-cypress-io-e313d3c68988

### Pupeteer

+ https://pptr.dev/
+ https://puppetry.app/
+ https://github.com/checkly/headless-recorder

### LambdaTest:
Support says they support extensions
"you can test through automation testing by uploading a file to browser> extenstion> unpacked or packed extension"
* https://www.lambdatest.com/support/api-doc/#/extensions/UploadExtensions

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
## Integration tests: cypress + puppeteer

Fix #556.

---

This PR implements integration tests using **[Cypress](https://www.cypress.io/) + [Puppeteer](https://github.com/puppeteer/puppeteer).**

I have already added the following tests:
- [x] follow the welcome screen and connect using LNBits
- [x] follow the welcome screen and connect using BlueWallet
- [x] follow the welcome screen and create an Alby wallet

There are still more connections to the welcome screen, and other screens like spend and receive sats, connect and disconnect websites, lock and remove accounts. 

But we can do that in other PRs, the purpose of this PR is to start testing the extension so that the screens could have uniform paths and don't break due to any future change.

## How to test

Run the command: 
```bash
yarn run cy:open
```

## Preview
https://user-images.githubusercontent.com/5798170/155027049-b00e4914-3c53-4d90-b0f9-ec84c5ab491d.mp4

### CODE REVIEW

**Comment by escapedcat** [comment]
This is really amazing! Thanks @MiguelMedeiros !  ❤️ 

Some thought/feedbacl/questions to understand this a bit better:

- Testing flow from my understanding. Is this correct?:
  1. Cypress task runs node processes
  1. node process in this case is puppeter
  1. puppeter is executing tests on the extension
- Using puppeter directly would have the downside of not having a nice interface, video-recording, etc?
- This is testing chrome for now (which is fine), right? 
- Could this be added to GH actions in a following PR?
- Should the README be extended so people understand when they should run these tests?
- How about using [pptr-testing-library](https://testing-library.com/docs/pptr-testing-library/intro/) instead of selecting elements by `id` or `class`?

**Comment by MiguelMedeiros** [comment]
Thanks for your review and feedback @escapedcat :mage: !
Let me try to answer everything! :)

---


> * Testing flow from my understanding. Is this correct?:
>   
>   1. Cypress task runs node processes
>   2. node process in this case is puppeter
>   3. puppeter is executing tests on the extension

Yes.

> * Using puppeter directly would have the downside of not having a nice interface, video-recording, etc?

Yes, I've tried to use cypress only, but there is a problem when we try to visit pages with the protocol `chrome://extension`.
(take a look here: https://github.com/cypress-io/cypress/issues/1965)

So the solution for that was using Puppeteer inside Cypress, so we can have a nice interface for our test suit, videos, screenshots, gh actions easily integrated, etc.

> * This is testing chrome for now (which is fine), right?

Yep.

> * Could this be added to GH actions in a following PR?

Yes, we can integrate Cypress with GH actions, take a look at this video: 
https://youtu.be/uzAbSwAlX7Q?t=605

> * Should the README be extended so people understand when they should run these tests?

Sure! I forgot this! I'll push a commit with the instructions in the readme file!

> * How about using [pptr-testing-library](https://testing-library.com/docs/pptr-testing-library/intro/) instead of selecting elements by `id` or `class`?

Good idea!

**Comment by MiguelMedeiros** [comment]
Hey @escapedcat, 

Since we are already using Jest to make unit tests let me close this PR and open a new one with Puppeteer + Jest.
I will also add the `data-testids` and the readme instructions. 

HODL! :)

**Comment by escapedcat** [comment]
Re-opening this to compare it to #627

**Comment by escapedcat** [comment]
Was hoping that i.e. tracing/screenshots/videos on-failwork with Cypress. But it seems like both tools (Cypress and Playwright) have issues with that when using puppeteer.
There's a chaneg Cypress might support the extension tab in the future. We can check back again. when this is solved:
https://github.com/cypress-io/cypress/issues/1965

**Comment by escapedcat** [comment]
Related to #627

**Pull request closed without merging**
