### PR TITLE
fix: update keyboard shortcut to mv3

### PR DESCRIPTION
**Pull request by reneaaron**
### Describe the changes you have made in this PR

Action commands seem to have been moved with MV3: 

https://developer.chrome.com/docs/extensions/reference/commands/#action-commands

### CODE REVIEW

**Comment by reneaaron** [comment]
The keyboard shortcut doesn't work for me in chrome (at least not with the dev build) :thinking:

**Comment by bumi** [comment]
does it work with this?

**Comment by reneaaron** [comment]
No, only after setting it manually in the chrome settings: 

chrome://extensions/shortcuts

Don't know if that is because this shortcut might already be used.

**Comment by pavanjoshi914** [comment]
there is a bug in chrome, https://bugs.chromium.org/p/chromium/issues/detail?id=1478453#c_ts1695708024 it works for firefox currently maybe we merge it for now. since it will take time to get this fix from their side

**Pull request merged**
