### PR TITLE
refactor: use new input component to support dual currency on edit budget screen

### PR DESCRIPTION
**Pull request by secondl1ght**
### Describe the changes you have made in this PR
On the Edit Allowance screen I removed the TextField component in favor of the new DualCurrencyField component to support fiat values on this input element.

### Link this PR to an issue

#1016 

### Type of change (Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes (If any)

BEFORE:

image

AFTER:

image

### How has this been tested?

Ran locally and tested setting a new budget, checked console for any errors and verified new budget was set.

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [ ] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by secondl1ght** [comment]
NOTE: I also added a new prop to the DualCurrencyField component to support adding a hint text which will appear below the input element (it is optional). The TextField component had this functionality so I thought we should also have it in this new component.

**Comment by escapedcat** [comment]
Would be nice if the hint has the same style as the hint from the textfield-input

**Comment by secondl1ght** [comment]
I pushed a WIP fix for the unit test FAIL that is happening, it looks like the currency setting is undefined in this unit test environment. Which is weird because this setting has a default of USD. So I am trying to set this setting before the test runs but it is still not working. Any ideas here?

image
image

**Comment by secondl1ght** [comment]
> Would be nice if the hint has the same style as the hint from the textfield-input

Good call, I updated this to be the case.

**Comment by secondl1ght** [comment]
Merge conflicts resolved, unit test fixed and this is ready for final review and merging now.

**Review by escapedcat — APPROVED** [review]

**Pull request merged**
