### PR TITLE
Bug: Removed currencies which throw a 404

### LINKED ISSUE #1649: Bug: get fiat value for CUC fails with 404
### Describe the bug

While working on this PR https://github.com/getAlby/lightning-browser-extension/pull/1645
I saw that a conversion for sats to fiat for the currency "CUC" fails.

Sidenote:
In the [PR](https://github.com/getAlby/lightning-browser-extension/pull/1645) above I added a try/catch block which was missing.

### Screenshots of the changes [optional]

From the PR mentioned above

### To Reproduce

1. Open the settings page
2. Change the currency to CUC
3. watch the console for the error

### Expected behavior

No error is thrown or the currency can not be selected

### Alby information

- Alby Version: current master
- Alby installed through manually
- Wallet connected with Alby 

### Device information [optional]

- OS: Mac
- Browser FF
- Browser Version 105

### Are you working on this issue?

no

### PR DESCRIPTION
**Pull request by mviswanathsai**
### Describe the changes you have made in this PR

- Removed currencies from the constants.ts which throw an error

### Link this PR to an issue [optional]

Fixes #1649

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Checking if any of the currencies from the currency list on settings screen throw an error in the console 

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [ ] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

### CODE REVIEW

**Comment by bumi** [comment]
thanks for taking a look at this and this PR! great
I think the yarn.lock file should not change in this PR, can you remove this?

**Comment by mviswanathsai** [comment]
Thanks!
Sure

**Comment by mviswanathsai** [comment]
@bumi I have removed the yarn.lock file

**Comment by bumi** [comment]
sorry I mean this PR should not contain any changes on the yarn.lock file and only the changes of the constants. 
now it seems the yarn.lock file would be deleted.

**Comment by mviswanathsai** [comment]
@bumi My bad, I have changed it accordingly

**Comment by escapedcat** [comment]
@mviswanathsai fixed it for you. For next time, this is what I did:

```sh
git checkout master yarn.lock
```

To revert all changes from the lock-file in your branch.

**Review by escapedcat — APPROVED** [review]

**Comment by mviswanathsai** [comment]
@escapedcat Thanks for helping out!

**Comment by escapedcat** [comment]
Thanks for checking all the currencies and this PR!

**Comment by escapedcat** [comment]
Just nit-picking, have a look at our commit message conventions: https://github.com/getAlby/lightning-browser-extension/blob/master/doc/CONTRIBUTION.md#commit-message-format

**Pull request merged**
